import type { CompanyPriceBookUnit } from './companyPriceBook';

export type BravoCatalogStatus = 'draft' | 'testing' | 'approved' | 'deprecated' | 'archived';
export type BravoCatalogConfidenceLevel = 1 | 2 | 3 | 4 | 5;

export type BravoCatalogEstimateTemplate = {
    line_item_title: string;
    default_scope: string;
    pricing_notes: string[];
};

export type BravoMasterPlumbingCatalogItem = {
    service_id: string;
    price_key: string;
    version: string;
    status: BravoCatalogStatus;
    confidence_level: BravoCatalogConfidenceLevel;
    service_name: string;
    system: string;
    area: string;
    equipment: string;
    category: string;
    service_type: string;
    unit: CompanyPriceBookUnit;
    base_price: number | null;
    labor_hours: number | null;
    material_cost: number | null;
    linear_foot_price: number | null;
    minimum_price: number | null;
    maximum_discount_percent: number | null;
    package_discount_percent: number | null;
    customer_description: string;
    internal_description: string;
    whats_included: string[];
    whats_not_included: string[];
    common_add_ons: string[];
    recommended_upgrades: string[];
    required_photos: string[];
    required_videos: string[];
    required_measurements: string[];
    required_tests: string[];
    required_documents: string[];
    warranty: string;
    permit_required: boolean;
    code_notes: string[];
    safety_notes: string[];
    recommended_tools: string[];
    related_services: string[];
    estimate_template: BravoCatalogEstimateTemplate;
    ai_context: string;
    active: boolean;
};

const catalogVersion = '1.0';

const pricingPlaceholder = {
    base_price: null,
    labor_hours: null,
    material_cost: null,
    linear_foot_price: null,
    minimum_price: null,
    maximum_discount_percent: null,
    package_discount_percent: null,
};

export const bravoMasterPlumbingCatalogItems: BravoMasterPlumbingCatalogItem[] = [
    item({
        service_id: 'bravo-plumbing-001',
        price_key: 'water_service_garage_mechanical_standard_tank_water_heater_replacement',
        service_name: 'Standard tank water heater replacement',
        system: 'Water Service',
        area: 'Garage / Mechanical',
        equipment: 'Tank Water Heater',
        category: 'Water Heaters',
        service_type: 'replacement',
        unit: 'replacement',
        customer_description: 'Replace an existing standard residential tank water heater with a comparable unit.',
        internal_description: 'Use for like-kind tank water heater replacement after confirming size, fuel type, venting, access, code requirements, and haul-away scope.',
        whats_included: ['Remove existing tank water heater', 'Install replacement unit', 'Reconnect approved water and fuel connections', 'Basic startup check'],
        whats_not_included: ['Major venting changes', 'Platform rebuild', 'Electrical upgrades', 'Permit fees unless specified'],
        common_add_ons: ['Expansion tank', 'Water heater pan', 'Seismic straps', 'Code corrections'],
        recommended_upgrades: ['Expansion tank install', 'Water heater pan installation', 'Whole-home water shutoff installation'],
        required_photos: ['Existing water heater label', 'Full installation area', 'Venting or flue', 'Water and fuel connections', 'Drain pan area'],
        required_videos: [],
        required_measurements: ['Tank gallon size', 'Access width', 'Water heater height', 'Vent diameter where applicable'],
        required_tests: ['Hot water operation check', 'Leak check at connections', 'Temperature setting confirmation'],
        required_documents: ['Manufacturer model and serial information', 'Permit documentation if required'],
        warranty: 'Use company-approved workmanship warranty and manufacturer equipment warranty.',
        permit_required: true,
        code_notes: ['Follow local water heater installation code', 'Confirm expansion control requirements', 'Confirm seismic restraint requirements where applicable'],
        safety_notes: ['Shut off water and fuel before removal', 'Verify combustion air and venting where applicable'],
        recommended_tools: ['Pipe cutters', 'Adjustable wrenches', 'Level', 'Combustion leak detector where applicable'],
        related_services: ['water_service_garage_mechanical_water_heater_expansion_tank_installation', 'water_service_garage_mechanical_water_heater_pan_installation'],
        estimate_template: template('Standard tank water heater replacement', 'Replace existing tank water heater after confirming site conditions and code requirements.'),
        ai_context: 'Ask for tank size, fuel type, venting, access constraints, permit requirements, expansion tank status, pan/drain status, and haul-away requirements.',
    }),
    item({
        service_id: 'bravo-plumbing-002',
        price_key: 'water_service_garage_mechanical_tankless_water_heater_replacement',
        service_name: 'Tankless water heater replacement',
        system: 'Water Service',
        area: 'Garage / Mechanical',
        equipment: 'Tankless Water Heater',
        category: 'Water Heaters',
        service_type: 'replacement',
        unit: 'replacement',
        customer_description: 'Replace an existing residential tankless water heater.',
        internal_description: 'Use for tankless replacement after confirming gas sizing, venting, condensate routing, water treatment, isolation valves, and electrical requirements.',
        whats_included: ['Remove existing tankless unit', 'Install replacement tankless unit', 'Reconnect water and fuel connections', 'Basic startup check'],
        whats_not_included: ['Gas line resizing', 'New vent route', 'Electrical circuit changes', 'Water treatment equipment'],
        common_add_ons: ['Isolation valve kit', 'Condensate neutralizer', 'Water treatment', 'Gas line correction'],
        recommended_upgrades: ['Whole-home filter install', 'Tankless isolation valve kit', 'Recirculation pump service'],
        required_photos: ['Existing unit label', 'Full wall mounting area', 'Venting', 'Gas connection', 'Condensate routing'],
        required_videos: [],
        required_measurements: ['Unit model', 'Gas pipe size', 'Vent size and route', 'Available wall space'],
        required_tests: ['Leak check', 'Hot water flow test', 'Error code check after startup'],
        required_documents: ['Manufacturer startup information', 'Permit documentation if required'],
        warranty: 'Use company-approved workmanship warranty and manufacturer equipment warranty.',
        permit_required: true,
        code_notes: ['Confirm venting material and termination clearances', 'Confirm condensate disposal requirements'],
        safety_notes: ['Verify gas shutoff operation', 'Check for combustion safety concerns before startup'],
        recommended_tools: ['Combustion analyzer where required', 'Gas leak detector', 'Pipe wrenches', 'Level'],
        related_services: ['water_service_garage_mechanical_recirculation_pump_installation', 'water_quality_whole_home_whole_home_filter_installation'],
        estimate_template: template('Tankless water heater replacement', 'Replace existing tankless water heater after confirming venting, fuel, condensate, and access requirements.'),
        ai_context: 'Ask for existing model, fuel type, vent type, gas line size, condensate setup, water quality, and whether this is like-kind replacement or conversion.',
    }),
    item({
        service_id: 'bravo-plumbing-003',
        price_key: 'water_service_garage_mechanical_water_heater_diagnostic',
        service_name: 'Water heater diagnostic',
        system: 'Water Service',
        area: 'Garage / Mechanical',
        equipment: 'Water Heater',
        category: 'Water Heaters',
        service_type: 'diagnostic',
        unit: 'diagnostic',
        customer_description: 'Diagnose water heater performance, leak, ignition, power, or code concerns.',
        internal_description: 'Use for first-visit water heater troubleshooting before repair or replacement pricing is known.',
        whats_included: ['Visual inspection', 'Basic operational checks', 'Findings summary', 'Repair or replacement recommendation'],
        whats_not_included: ['Parts replacement', 'Tank flush', 'Permit fees', 'Major disassembly'],
        common_add_ons: ['Water heater flush', 'T&P valve replacement', 'Expansion tank replacement'],
        recommended_upgrades: ['Water heater flush', 'Expansion tank install', 'Whole-home filter install'],
        required_photos: ['Water heater label', 'Full installation area', 'Observed leak or failure point'],
        required_videos: ['Short video of active leak or abnormal operation when safe'],
        required_measurements: ['Water temperature if relevant', 'Incoming water pressure if relevant'],
        required_tests: ['Visual leak check', 'Power or ignition check where applicable'],
        required_documents: [],
        warranty: 'Diagnostic visit warranty applies only to the performed evaluation, not unresolved hidden conditions.',
        permit_required: false,
        code_notes: ['Document visible code concerns separately from diagnostic findings'],
        safety_notes: ['Do not operate unsafe equipment', 'Shut down leaking or unsafe units when needed'],
        recommended_tools: ['Multimeter', 'Thermometer', 'Pressure gauge', 'Gas leak detector where applicable'],
        related_services: ['water_service_garage_mechanical_water_heater_flush', 'water_service_garage_mechanical_standard_tank_water_heater_replacement'],
        estimate_template: template('Water heater diagnostic', 'Diagnose water heater issue and provide repair or replacement recommendation.'),
        ai_context: 'Ask about water temperature, leak location, age, fuel type, error codes, recent changes, and whether hot water is fully out or intermittent.',
    }),
    item({
        service_id: 'bravo-plumbing-004',
        price_key: 'water_service_garage_mechanical_water_heater_flush',
        service_name: 'Water heater flush',
        system: 'Water Service',
        area: 'Garage / Mechanical',
        equipment: 'Water Heater',
        category: 'Water Heaters',
        service_type: 'maintenance',
        unit: 'service call',
        customer_description: 'Flush sediment from a residential water heater where conditions allow.',
        internal_description: 'Use for maintenance flush. Confirm age, drain valve condition, water quality, and whether flushing may worsen an old or compromised tank.',
        whats_included: ['Connect hose to drain valve', 'Flush tank as accessible', 'Check visible connections after flush'],
        whats_not_included: ['Replacing failed drain valve', 'Descaling tankless unit', 'Repairing leaks discovered during service'],
        common_add_ons: ['Drain valve replacement', 'Anode rod inspection', 'Expansion tank check'],
        recommended_upgrades: ['Whole-home filter install', 'Expansion tank install'],
        required_photos: ['Water heater label', 'Drain valve', 'Flush hose setup'],
        required_videos: [],
        required_measurements: ['Tank age', 'Water pressure if relevant'],
        required_tests: ['Post-service leak check', 'Hot water recovery confirmation where practical'],
        required_documents: [],
        warranty: 'Maintenance service warranty covers workmanship only.',
        permit_required: false,
        code_notes: [],
        safety_notes: ['Use caution with hot water discharge', 'Do not force compromised drain valves'],
        recommended_tools: ['Hose', 'Bucket', 'Channel locks', 'Thermometer'],
        related_services: ['water_service_garage_mechanical_water_heater_drain_valve_replacement', 'water_service_garage_mechanical_water_heater_diagnostic'],
        estimate_template: template('Water heater flush', 'Flush accessible residential water heater and check for visible leaks after service.'),
        ai_context: 'Ask for tank age, last flush date, visible sediment issues, drain valve condition, and whether the customer has a floor drain or safe discharge point.',
    }),
    item({
        service_id: 'bravo-plumbing-005',
        price_key: 'water_service_garage_mechanical_water_heater_expansion_tank_installation',
        service_name: 'Expansion tank install',
        system: 'Water Service',
        area: 'Garage / Mechanical',
        equipment: 'Expansion Tank',
        category: 'Water Heaters',
        service_type: 'installation',
        unit: 'install',
        customer_description: 'Install a potable water expansion tank for a residential water heater system.',
        internal_description: 'Use when expansion control is missing, failed, or required by local code or closed plumbing system conditions.',
        whats_included: ['Install approved expansion tank', 'Set precharge as practical', 'Leak check connections'],
        whats_not_included: ['Replacing water heater', 'PRV replacement', 'Major piping relocation'],
        common_add_ons: ['PRV replacement', 'Water pressure inspection', 'Water heater code correction'],
        recommended_upgrades: ['PRV replacement', 'Water pressure inspection'],
        required_photos: ['Water heater area', 'Cold water piping', 'Installed expansion tank'],
        required_videos: [],
        required_measurements: ['Static water pressure', 'Tank size requirement when known'],
        required_tests: ['Leak check', 'Pressure check'],
        required_documents: [],
        warranty: 'Use company-approved workmanship warranty and manufacturer equipment warranty.',
        permit_required: false,
        code_notes: ['Confirm local expansion control requirements'],
        safety_notes: ['Support expansion tank properly', 'Confirm water is off before piping modification'],
        recommended_tools: ['Pressure gauge', 'Pipe cutters', 'Adjustable wrenches', 'Air gauge'],
        related_services: ['water_service_garage_mechanical_prv_pressure_regulator_replacement', 'diagnostics_inspections_whole_home_water_pressure_inspection'],
        estimate_template: template('Expansion tank install', 'Install potable water expansion tank and verify connection is leak free.'),
        ai_context: 'Ask whether the home has a PRV or closed plumbing system, current water pressure, water heater size, and available mounting location.',
    }),
    item({
        service_id: 'bravo-plumbing-006',
        price_key: 'water_service_garage_mechanical_prv_pressure_regulator_replacement',
        service_name: 'PRV replacement',
        system: 'Water Service',
        area: 'Garage / Mechanical',
        equipment: 'Pressure Reducing Valve',
        category: 'Valves / Shutoffs',
        service_type: 'replacement',
        unit: 'replacement',
        customer_description: 'Replace a failed or aging pressure reducing valve.',
        internal_description: 'Use for accessible PRV replacement after confirming shutoff access, pipe material, pressure readings, and access constraints.',
        whats_included: ['Remove existing accessible PRV', 'Install replacement PRV', 'Set pressure target as practical', 'Leak check'],
        whats_not_included: ['Main shutoff replacement', 'Wall repair', 'Pressure issues caused by hidden piping conditions'],
        common_add_ons: ['Main water shutoff replacement', 'Expansion tank install', 'Water pressure inspection'],
        recommended_upgrades: ['Main water shutoff replacement', 'Expansion tank install'],
        required_photos: ['Existing PRV', 'Nearby shutoff valves', 'Pipe material and access'],
        required_videos: [],
        required_measurements: ['Static water pressure before service', 'Static water pressure after service', 'Pipe size'],
        required_tests: ['Pressure test after replacement', 'Leak check'],
        required_documents: [],
        warranty: 'Use company-approved workmanship warranty and manufacturer equipment warranty.',
        permit_required: false,
        code_notes: ['Confirm allowable pressure range for local code and fixtures'],
        safety_notes: ['Confirm reliable water shutoff before cutting piping'],
        recommended_tools: ['Pressure gauge', 'Pipe cutters', 'Press or solder tools as applicable'],
        related_services: ['water_service_garage_mechanical_main_water_shutoff_replacement', 'water_service_garage_mechanical_water_heater_expansion_tank_installation'],
        estimate_template: template('PRV replacement', 'Replace accessible pressure reducing valve and adjust pressure after installation.'),
        ai_context: 'Ask for current pressure, symptoms, PRV location, pipe type, shutoff condition, and whether an expansion tank is installed.',
    }),
    item({
        service_id: 'bravo-plumbing-007',
        price_key: 'water_service_garage_mechanical_main_water_shutoff_replacement',
        service_name: 'Main water shutoff replacement',
        system: 'Water Service',
        area: 'Garage / Mechanical',
        equipment: 'Main Shutoff Valve',
        category: 'Valves / Shutoffs',
        service_type: 'replacement',
        unit: 'replacement',
        customer_description: 'Replace the primary water shutoff valve serving the home.',
        internal_description: 'Use for accessible main shutoff valve replacement. Confirm upstream shutoff, pipe material, and whether utility coordination is required.',
        whats_included: ['Remove accessible existing shutoff', 'Install replacement shutoff valve', 'Restore water and leak check'],
        whats_not_included: ['Utility meter repair', 'Excavation', 'Wall restoration', 'PRV replacement unless specified'],
        common_add_ons: ['PRV replacement', 'Whole-home shutoff installation', 'Pressure test'],
        recommended_upgrades: ['PRV replacement', 'Whole-home water shutoff installation'],
        required_photos: ['Existing shutoff', 'Pipe material', 'Access area', 'Meter or upstream shutoff if relevant'],
        required_videos: [],
        required_measurements: ['Pipe size', 'Access clearance'],
        required_tests: ['Leak check', 'Water restoration confirmation'],
        required_documents: ['Utility coordination notes when required'],
        warranty: 'Use company-approved workmanship warranty and manufacturer equipment warranty.',
        permit_required: false,
        code_notes: ['Confirm approved valve type for potable water service'],
        safety_notes: ['Verify upstream water control before cutting piping'],
        recommended_tools: ['Pipe cutters', 'Press or solder tools as applicable', 'Adjustable wrenches'],
        related_services: ['water_service_garage_mechanical_prv_pressure_regulator_replacement', 'water_service_whole_home_pressure_test_water_system'],
        estimate_template: template('Main water shutoff replacement', 'Replace accessible main water shutoff valve and verify leak-free operation.'),
        ai_context: 'Ask where the shutoff is located, pipe material, whether it fully shuts off, and whether utility/meter shutoff access is available.',
    }),
    item({
        service_id: 'bravo-plumbing-008',
        price_key: 'water_service_bathroom_bathroom_angle_stop_replacement',
        service_name: 'Angle stop replacement',
        system: 'Water Service',
        area: 'Bathroom',
        equipment: 'Fixture Shutoff Valve',
        category: 'Valves / Shutoffs',
        service_type: 'replacement',
        unit: 'each',
        customer_description: 'Replace an accessible fixture shutoff valve.',
        internal_description: 'Use for angle stop replacement at sinks, toilets, and similar fixtures. Price per valve unless bundled.',
        whats_included: ['Shut off water', 'Replace accessible angle stop', 'Reconnect existing supply line if suitable', 'Leak check'],
        whats_not_included: ['Wall repair', 'Replacing damaged stub-out piping', 'Fixture replacement'],
        common_add_ons: ['Supply line replacement', 'Toilet repair', 'Faucet replacement'],
        recommended_upgrades: ['Supply line replacement'],
        required_photos: ['Existing angle stop', 'Fixture area', 'Stub-out condition'],
        required_videos: [],
        required_measurements: ['Valve size or connection type when visible'],
        required_tests: ['Leak check', 'Valve operation check'],
        required_documents: [],
        warranty: 'Use company-approved workmanship warranty.',
        permit_required: false,
        code_notes: ['Use approved potable water valve and supply connection'],
        safety_notes: ['Confirm water shutoff before removing valve'],
        recommended_tools: ['Adjustable wrench', 'Tubing cutter', 'Supply line wrench'],
        related_services: ['water_service_bathroom_bathroom_supply_line_replacement', 'water_service_bathroom_toilet_shutoff_replacement'],
        estimate_template: template('Angle stop replacement', 'Replace accessible fixture shutoff valve and verify leak-free operation.'),
        ai_context: 'Ask how many valves, fixture type, connection type, corrosion level, and whether supply lines should be replaced.',
    }),
    item({
        service_id: 'bravo-plumbing-009',
        price_key: 'water_service_kitchen_kitchen_faucet_replacement',
        service_name: 'Kitchen faucet replacement',
        system: 'Water Service',
        area: 'Kitchen',
        equipment: 'Kitchen Faucet',
        category: 'Faucets / Sinks',
        service_type: 'replacement',
        unit: 'replacement',
        customer_description: 'Replace a kitchen faucet with a customer-approved fixture.',
        internal_description: 'Use for kitchen faucet replacement after confirming sink hole layout, shutoff condition, disposal/RO conflicts, and customer-supplied versus company-supplied fixture.',
        whats_included: ['Remove existing faucet', 'Install replacement faucet', 'Reconnect supplies', 'Leak check'],
        whats_not_included: ['Countertop modification', 'Sink replacement', 'Failed shutoff valve replacement unless specified'],
        common_add_ons: ['Angle stop replacement', 'Supply line replacement', 'RO faucet replacement'],
        recommended_upgrades: ['Kitchen angle stop replacement', 'Kitchen supply line replacement'],
        required_photos: ['Existing faucet', 'Under-sink connections', 'Sink hole layout'],
        required_videos: [],
        required_measurements: ['Sink hole count', 'Deck thickness if unusual'],
        required_tests: ['Hot and cold operation check', 'Leak check under sink'],
        required_documents: ['Fixture model information when customer supplied'],
        warranty: 'Use company-approved workmanship warranty; fixture warranty depends on manufacturer.',
        permit_required: false,
        code_notes: [],
        safety_notes: ['Confirm shutoffs work before disconnecting supplies'],
        recommended_tools: ['Basin wrench', 'Adjustable wrench', 'Plumber putty or sealant as required'],
        related_services: ['water_service_kitchen_kitchen_angle_stop_replacement', 'water_service_kitchen_kitchen_supply_line_replacement'],
        estimate_template: template('Kitchen faucet replacement', 'Replace kitchen faucet and verify operation and leak-free connections.'),
        ai_context: 'Ask whether fixture is customer supplied, sink hole count, shutoff condition, and whether accessories like sprayer, soap dispenser, or RO faucet are involved.',
    }),
    item({
        service_id: 'bravo-plumbing-010',
        price_key: 'water_service_bathroom_bathroom_faucet_replacement',
        service_name: 'Bathroom faucet replacement',
        system: 'Water Service',
        area: 'Bathroom',
        equipment: 'Bathroom Faucet',
        category: 'Faucets / Sinks',
        service_type: 'replacement',
        unit: 'replacement',
        customer_description: 'Replace a bathroom sink faucet.',
        internal_description: 'Use for lavatory faucet replacement after confirming faucet spread, pop-up assembly, shutoffs, and supply lines.',
        whats_included: ['Remove existing faucet', 'Install replacement faucet', 'Reconnect supplies', 'Basic drain connection check'],
        whats_not_included: ['Sink replacement', 'Countertop modification', 'Failed shutoff replacement unless specified'],
        common_add_ons: ['Pop-up assembly replacement', 'Angle stop replacement', 'Supply line replacement'],
        recommended_upgrades: ['Bathroom angle stop replacement', 'Bathroom P-trap replacement'],
        required_photos: ['Existing faucet', 'Under-sink connections', 'Drain assembly'],
        required_videos: [],
        required_measurements: ['Faucet spread', 'Sink hole count'],
        required_tests: ['Hot and cold operation check', 'Leak check'],
        required_documents: ['Fixture model information when customer supplied'],
        warranty: 'Use company-approved workmanship warranty; fixture warranty depends on manufacturer.',
        permit_required: false,
        code_notes: [],
        safety_notes: ['Confirm shutoffs work before disconnecting supplies'],
        recommended_tools: ['Basin wrench', 'Adjustable wrench', 'Plumber putty or sealant as required'],
        related_services: ['drain_sewer_bathroom_pop_up_assembly_replacement', 'water_service_bathroom_bathroom_angle_stop_replacement'],
        estimate_template: template('Bathroom faucet replacement', 'Replace bathroom sink faucet and verify operation and leak-free connections.'),
        ai_context: 'Ask faucet spread, customer-supplied fixture status, drain pop-up condition, and shutoff condition.',
    }),
    item({
        service_id: 'bravo-plumbing-011',
        price_key: 'water_service_bathroom_toilet_replacement',
        service_name: 'Toilet replacement',
        system: 'Water Service',
        area: 'Bathroom',
        equipment: 'Toilet',
        category: 'Toilets',
        service_type: 'replacement',
        unit: 'replacement',
        customer_description: 'Replace a residential toilet.',
        internal_description: 'Use for toilet replacement after confirming rough-in, flange condition, shutoff condition, flooring, and haul-away scope.',
        whats_included: ['Remove existing toilet', 'Install replacement toilet', 'Replace wax or seal', 'Leak and flush test'],
        whats_not_included: ['Flange repair', 'Floor repair', 'Toilet supply valve replacement unless specified'],
        common_add_ons: ['Toilet flange repair', 'Toilet shutoff replacement', 'Haul-away fee'],
        recommended_upgrades: ['Toilet shutoff replacement', 'Toilet supply line replacement'],
        required_photos: ['Existing toilet', 'Toilet base and floor', 'Shutoff valve', 'Flange after removal if condition issue found'],
        required_videos: [],
        required_measurements: ['Toilet rough-in', 'Bathroom access clearance'],
        required_tests: ['Flush test', 'Leak check at base and supply'],
        required_documents: ['Toilet model information when customer supplied'],
        warranty: 'Use company-approved workmanship warranty; fixture warranty depends on manufacturer.',
        permit_required: false,
        code_notes: ['Confirm approved low-flow fixture requirements where applicable'],
        safety_notes: ['Use safe lifting practices', 'Protect finished flooring'],
        recommended_tools: ['Closet auger', 'Adjustable wrench', 'Wax ring or approved seal', 'Level'],
        related_services: ['drain_sewer_bathroom_toilet_flange_repair', 'water_service_bathroom_toilet_shutoff_replacement'],
        estimate_template: template('Toilet replacement', 'Replace residential toilet and verify flush performance and leak-free operation.'),
        ai_context: 'Ask rough-in size, customer-supplied fixture status, flange condition, floor condition, shutoff condition, and haul-away requirement.',
    }),
    item({
        service_id: 'bravo-plumbing-012',
        price_key: 'water_service_bathroom_toilet_repair',
        service_name: 'Toilet repair',
        system: 'Water Service',
        area: 'Bathroom',
        equipment: 'Toilet',
        category: 'Toilets',
        service_type: 'repair',
        unit: 'repair',
        customer_description: 'Repair a running, leaking, loose, or malfunctioning toilet.',
        internal_description: 'Use for common toilet tank, supply, or reset repairs after diagnosing the actual failure.',
        whats_included: ['Toilet inspection', 'Minor tank or connection repair as scoped', 'Flush and leak test'],
        whats_not_included: ['Toilet replacement', 'Major flange repair', 'Floor repair'],
        common_add_ons: ['Fill valve replacement', 'Flush valve replacement', 'Toilet reset', 'Toilet shutoff replacement'],
        recommended_upgrades: ['Toilet replacement when fixture is cracked or obsolete'],
        required_photos: ['Toilet', 'Tank components', 'Leak location if visible'],
        required_videos: ['Short video of running toilet or leak when safe'],
        required_measurements: [],
        required_tests: ['Flush test', 'Dye test when relevant', 'Leak check'],
        required_documents: [],
        warranty: 'Use company-approved workmanship warranty for repaired components.',
        permit_required: false,
        code_notes: [],
        safety_notes: ['Shut off water for active leaks', 'Protect flooring around toilet base'],
        recommended_tools: ['Toilet repair kit', 'Adjustable wrench', 'Dye tablets', 'Closet auger'],
        related_services: ['water_service_bathroom_fill_valve_replacement', 'water_service_bathroom_toilet_reset'],
        estimate_template: template('Toilet repair', 'Diagnose and repair common toilet issue, then verify flush and leak-free operation.'),
        ai_context: 'Ask whether toilet is running, leaking, clogged, loose, cracked, or not flushing, and whether water can be shut off.',
    }),
    item({
        service_id: 'bravo-plumbing-013',
        price_key: 'drain_sewer_kitchen_garbage_disposal_replacement',
        service_name: 'Garbage disposal replacement',
        system: 'Drain / Sewer',
        area: 'Kitchen',
        equipment: 'Garbage Disposal',
        category: 'Drains / Sewer',
        service_type: 'replacement',
        unit: 'replacement',
        customer_description: 'Replace a residential kitchen garbage disposal.',
        internal_description: 'Use for disposal replacement after confirming power, switch, drain configuration, dishwasher connection, and customer-supplied versus company-supplied unit.',
        whats_included: ['Remove existing disposal', 'Install replacement disposal', 'Reconnect drain and dishwasher connection when applicable', 'Leak and operation check'],
        whats_not_included: ['Electrical switch repair', 'Kitchen drain rebuild beyond disposal connection', 'Dishwasher replacement'],
        common_add_ons: ['Dishwasher drain connection', 'Kitchen tubular waste rebuild', 'Air gap replacement'],
        recommended_upgrades: ['Kitchen sink drain rebuild', 'Dishwasher air gap replacement'],
        required_photos: ['Existing disposal', 'Under-sink drain piping', 'Electrical connection area'],
        required_videos: [],
        required_measurements: ['Sink flange size if unusual'],
        required_tests: ['Operation test', 'Leak check', 'Dishwasher drain check when connected'],
        required_documents: ['Disposal model information when customer supplied'],
        warranty: 'Use company-approved workmanship warranty; disposal warranty depends on manufacturer.',
        permit_required: false,
        code_notes: ['Confirm local dishwasher drain and air gap requirements'],
        safety_notes: ['Disconnect power before handling disposal wiring', 'Do not place hands inside disposal chamber'],
        recommended_tools: ['Disposal wrench', 'Screwdrivers', 'Pliers', 'Plumber putty or approved sealant'],
        related_services: ['drain_sewer_kitchen_dishwasher_air_gap_replacement', 'drain_sewer_kitchen_kitchen_tubular_waste_rebuild'],
        estimate_template: template('Garbage disposal replacement', 'Replace garbage disposal and verify operation and leak-free drain connections.'),
        ai_context: 'Ask if disposal is hardwired or corded, dishwasher connected, unit size, symptoms, and whether replacement is customer supplied.',
    }),
    item({
        service_id: 'bravo-plumbing-014',
        price_key: 'water_service_bathroom_shower_cartridge_replacement',
        service_name: 'Shower cartridge replacement',
        system: 'Water Service',
        area: 'Bathroom',
        equipment: 'Shower Valve',
        category: 'Fixtures',
        service_type: 'replacement',
        unit: 'replacement',
        customer_description: 'Replace a shower valve cartridge to address leaking, temperature, or control issues.',
        internal_description: 'Use when valve body is serviceable and cartridge replacement is appropriate. Confirm brand, access, corrosion, and shutoff availability.',
        whats_included: ['Remove trim as needed', 'Replace compatible cartridge', 'Reassemble trim', 'Test operation'],
        whats_not_included: ['Valve body replacement', 'Tile repair', 'Access panel creation', 'Unavailable or seized cartridge complications'],
        common_add_ons: ['Shower valve replacement', 'Trim replacement', 'Whole-home shutoff service'],
        recommended_upgrades: ['Shower valve replacement when valve is obsolete or damaged'],
        required_photos: ['Shower trim', 'Valve with trim removed if available', 'Brand markings'],
        required_videos: ['Short video of leak or temperature issue when useful'],
        required_measurements: [],
        required_tests: ['Hot/cold operation check', 'Leak check', 'Temperature control check'],
        required_documents: ['Cartridge model or brand notes when known'],
        warranty: 'Use company-approved workmanship warranty for installed cartridge.',
        permit_required: false,
        code_notes: ['Confirm anti-scald function where applicable'],
        safety_notes: ['Confirm water shutoff before cartridge removal', 'Use caution with seized cartridges'],
        recommended_tools: ['Cartridge puller', 'Screwdrivers', 'Allen keys', 'Plumber grease'],
        related_services: ['water_service_bathroom_shower_valve_replacement', 'water_service_whole_home_emergency_water_shutoff_service'],
        estimate_template: template('Shower cartridge replacement', 'Replace compatible shower cartridge and verify leak-free operation.'),
        ai_context: 'Ask brand, symptoms, age, whether water shuts off, trim style, and whether cartridge is seized or previously serviced.',
    }),
    item({
        service_id: 'bravo-plumbing-015',
        price_key: 'water_service_bathroom_shower_valve_replacement',
        service_name: 'Shower valve replacement',
        system: 'Water Service',
        area: 'Bathroom',
        equipment: 'Shower Valve',
        category: 'Fixtures',
        service_type: 'replacement',
        unit: 'replacement',
        customer_description: 'Replace a shower valve body when repair is not practical or desired.',
        internal_description: 'Use for shower valve replacement after confirming access method, wall finish, valve type, trim selection, and restoration responsibilities.',
        whats_included: ['Remove existing accessible valve', 'Install replacement valve', 'Connect water piping', 'Basic leak and operation test'],
        whats_not_included: ['Tile repair', 'Drywall restoration', 'Major repipe', 'Trim upgrades unless specified'],
        common_add_ons: ['Access opening coordination', 'Trim kit installation', 'Tub spout replacement'],
        recommended_upgrades: ['Pressure-balanced valve', 'New trim kit'],
        required_photos: ['Existing trim', 'Backside access if available', 'Wall finish', 'Valve area after opening'],
        required_videos: [],
        required_measurements: ['Wall thickness if relevant', 'Pipe size and material', 'Valve depth requirement'],
        required_tests: ['Pressure/leak test', 'Hot/cold operation check', 'Temperature limit check'],
        required_documents: ['Valve and trim model information', 'Permit documentation if required'],
        warranty: 'Use company-approved workmanship warranty and manufacturer equipment warranty.',
        permit_required: true,
        code_notes: ['Confirm anti-scald and pressure-balance requirements', 'Confirm local permit requirements'],
        safety_notes: ['Protect finished surfaces', 'Confirm water shutoff before opening piping'],
        recommended_tools: ['Pipe cutters', 'Press or solder tools as applicable', 'Level', 'Torch shield where soldering'],
        related_services: ['water_service_bathroom_shower_cartridge_replacement', 'diagnostics_inspections_other_access_opening_coordination'],
        estimate_template: template('Shower valve replacement', 'Replace shower valve body and verify leak-free operation before wall closure.'),
        ai_context: 'Ask access method, wall finish, valve brand, pipe material, trim selection, and whether restoration is included or excluded.',
    }),
    item({
        service_id: 'bravo-plumbing-016',
        price_key: 'drain_sewer_whole_home_drain_cleaning',
        service_name: 'Drain cleaning',
        system: 'Drain / Sewer',
        area: 'Whole Home',
        equipment: 'Drain Line',
        category: 'Drains / Sewer',
        service_type: 'service',
        unit: 'service call',
        customer_description: 'Clear an accessible drain stoppage.',
        internal_description: 'Use for accessible branch or fixture drain cleaning. Identify drain location, cleanout access, backup severity, and repeat stoppage history.',
        whats_included: ['Attempt to clear accessible stoppage', 'Basic flow test', 'Service findings summary'],
        whats_not_included: ['Camera inspection unless specified', 'Hydro jetting', 'Pipe repair', 'Multiple unrelated stoppages'],
        common_add_ons: ['Sewer camera inspection', 'Cleanout installation', 'P-trap replacement'],
        recommended_upgrades: ['Camera inspection for repeat stoppages'],
        required_photos: ['Affected fixture or drain', 'Cleanout access', 'Debris or roots if recovered'],
        required_videos: ['Short video of backup or post-service flow when useful'],
        required_measurements: ['Cable distance if tracked'],
        required_tests: ['Flow test after cleaning'],
        required_documents: [],
        warranty: 'Drain cleaning warranty depends on company policy and line condition.',
        permit_required: false,
        code_notes: [],
        safety_notes: ['Use PPE for sewage exposure', 'Protect finished surfaces from drain equipment'],
        recommended_tools: ['Drain machine', 'Hand auger', 'PPE', 'Drop cloths'],
        related_services: ['drain_sewer_whole_home_sewer_camera_inspection', 'drain_sewer_exterior_cleanout_installation'],
        estimate_template: template('Drain cleaning', 'Clear accessible drain stoppage and verify flow after service.'),
        ai_context: 'Ask which fixtures are affected, whether sewage is backing up, cleanout access, repeat history, and whether multiple drains are involved.',
    }),
    item({
        service_id: 'bravo-plumbing-017',
        price_key: 'drain_sewer_whole_home_main_line_cleanout',
        service_name: 'Main line cleanout',
        system: 'Drain / Sewer',
        area: 'Whole Home',
        equipment: 'Main Sewer Line',
        category: 'Drains / Sewer',
        service_type: 'service',
        unit: 'service call',
        customer_description: 'Clear a main sewer line stoppage from an accessible cleanout.',
        internal_description: 'Use when main line stoppage is suspected and an accessible cleanout is available.',
        whats_included: ['Access cleanout', 'Cable main line as scoped', 'Flow test when practical', 'Report findings'],
        whats_not_included: ['Excavation', 'Camera inspection unless specified', 'Hydro jetting', 'Pipe repair'],
        common_add_ons: ['Sewer camera inspection', 'Hydro jetting scope', 'Cleanout cap replacement'],
        recommended_upgrades: ['Sewer camera inspection after clearing'],
        required_photos: ['Cleanout location', 'Cleanout condition', 'Affected fixtures', 'Recovered roots or debris'],
        required_videos: ['Backup condition when useful'],
        required_measurements: ['Cable distance if tracked'],
        required_tests: ['Multi-fixture flow test after clearing'],
        required_documents: [],
        warranty: 'Main line cleaning warranty depends on company policy and line condition.',
        permit_required: false,
        code_notes: [],
        safety_notes: ['Use PPE for sewage exposure', 'Control spill and contamination risk'],
        recommended_tools: ['Main line machine', 'PPE', 'Cleanout tools', 'Drop cloths'],
        related_services: ['drain_sewer_whole_home_sewer_camera_inspection', 'drain_sewer_exterior_sewer_cleanout_cap_replacement'],
        estimate_template: template('Main line cleanout', 'Clear main sewer stoppage through accessible cleanout and verify restored flow.'),
        ai_context: 'Ask whether all drains are affected, cleanout location, overflow status, repeat history, roots, and whether camera inspection is desired.',
    }),
    item({
        service_id: 'bravo-plumbing-018',
        price_key: 'drain_sewer_whole_home_sewer_camera_inspection',
        service_name: 'Sewer camera inspection',
        system: 'Drain / Sewer',
        area: 'Whole Home',
        equipment: 'Sewer Line',
        category: 'Drains / Sewer',
        service_type: 'inspection',
        unit: 'inspection',
        customer_description: 'Camera inspect accessible sewer piping and document findings.',
        internal_description: 'Use for sewer video inspection when suitable access exists. Document access point, distance, findings, and limitations.',
        whats_included: ['Camera inspection from accessible entry point', 'Findings summary', 'Photos or video capture when available'],
        whats_not_included: ['Drain cleaning unless specified', 'Locating every line path', 'Excavation', 'Repair work'],
        common_add_ons: ['Line locate', 'Drain cleaning', 'Sewer repair estimate'],
        recommended_upgrades: ['Main line cleanout before inspection if blocked'],
        required_photos: ['Access point', 'Monitor findings', 'Cleanout or entry point'],
        required_videos: ['Inspection recording when equipment supports it'],
        required_measurements: ['Distance to defect or blockage', 'Pipe depth if located'],
        required_tests: ['Camera pass documentation'],
        required_documents: ['Inspection notes or report'],
        warranty: 'Inspection documents visible conditions at time of service only.',
        permit_required: false,
        code_notes: [],
        safety_notes: ['Use PPE around sewer access', 'Do not force camera through risky obstructions'],
        recommended_tools: ['Sewer camera', 'Locator where applicable', 'PPE'],
        related_services: ['drain_sewer_whole_home_main_line_cleanout', 'drain_sewer_whole_home_sewer_line_repair_estimate'],
        estimate_template: template('Sewer camera inspection', 'Camera inspect accessible sewer line and document visible findings and limitations.'),
        ai_context: 'Ask access point, reason for inspection, repeat stoppages, home sale context, and whether line locating is needed.',
    }),
    item({
        service_id: 'bravo-plumbing-019',
        price_key: 'drain_sewer_kitchen_p_trap_replacement',
        service_name: 'P-trap replacement',
        system: 'Drain / Sewer',
        area: 'Kitchen',
        equipment: 'P-trap',
        category: 'Drains / Sewer',
        service_type: 'replacement',
        unit: 'replacement',
        customer_description: 'Replace an accessible sink P-trap assembly.',
        internal_description: 'Use for accessible P-trap replacement under sink or utility fixture. Confirm material, trap size, and surrounding drain condition.',
        whats_included: ['Remove existing accessible P-trap', 'Install replacement trap assembly', 'Leak check'],
        whats_not_included: ['Wall drain repair', 'Sink replacement', 'Full tubular waste rebuild unless specified'],
        common_add_ons: ['Tubular drain replacement', 'Basket strainer replacement', 'Drain cleaning'],
        recommended_upgrades: ['Tubular drain replacement if nearby fittings are aged or leaking'],
        required_photos: ['Existing P-trap', 'Under-sink drain piping', 'Leak location'],
        required_videos: [],
        required_measurements: ['Trap size', 'Pipe material'],
        required_tests: ['Sink fill and drain test', 'Leak check'],
        required_documents: [],
        warranty: 'Use company-approved workmanship warranty.',
        permit_required: false,
        code_notes: ['Maintain proper trap configuration and slope'],
        safety_notes: ['Use PPE for drain residue', 'Protect cabinet base from water'],
        recommended_tools: ['Pliers', 'Tubing cutter', 'Bucket', 'PPE'],
        related_services: ['drain_sewer_kitchen_tubular_drain_replacement', 'drain_sewer_kitchen_kitchen_sink_stoppage'],
        estimate_template: template('P-trap replacement', 'Replace accessible P-trap assembly and verify leak-free drainage.'),
        ai_context: 'Ask fixture type, leak location, material, pipe size, and whether nearby tubular drain parts also need replacement.',
    }),
    item({
        service_id: 'bravo-plumbing-020',
        price_key: 'water_service_kitchen_dishwasher_supply_line_installation',
        service_name: 'Dishwasher connection',
        system: 'Water Service',
        area: 'Kitchen',
        equipment: 'Dishwasher',
        category: 'Laundry / Dishwasher',
        service_type: 'installation',
        unit: 'install',
        customer_description: 'Connect dishwasher water and drain lines where rough-in conditions are ready.',
        internal_description: 'Use for dishwasher connection scope, not appliance installation requiring cabinetry or electrical work.',
        whats_included: ['Connect dishwasher water supply as scoped', 'Connect drain line as scoped', 'Leak check'],
        whats_not_included: ['Electrical work', 'Cabinet modification', 'Dishwasher mounting or appliance warranty work unless specified'],
        common_add_ons: ['Dishwasher valve replacement', 'Air gap installation', 'Drain line replacement'],
        recommended_upgrades: ['Dishwasher air gap installation', 'Dishwasher water valve replacement'],
        required_photos: ['Dishwasher bay', 'Under-sink connection area', 'Supply valve', 'Drain connection'],
        required_videos: [],
        required_measurements: ['Supply line route', 'Drain hose route'],
        required_tests: ['Fill and drain test', 'Leak check'],
        required_documents: ['Appliance model information when relevant'],
        warranty: 'Use company-approved workmanship warranty for plumbing connections only.',
        permit_required: false,
        code_notes: ['Confirm local air gap or high loop requirements'],
        safety_notes: ['Do not perform electrical work under plumbing scope', 'Protect cabinets from leaks'],
        recommended_tools: ['Adjustable wrench', 'Pliers', 'Bucket', 'Supply line tools'],
        related_services: ['drain_sewer_kitchen_dishwasher_air_gap_installation', 'water_service_kitchen_dishwasher_water_valve_replacement'],
        estimate_template: template('Dishwasher connection', 'Connect dishwasher plumbing lines and verify fill, drain, and leak-free operation.'),
        ai_context: 'Ask whether dishwasher is already installed, supply valve condition, air gap/high loop requirement, drain route, and electrical status.',
    }),
    item({
        service_id: 'bravo-plumbing-021',
        price_key: 'water_service_kitchen_ice_maker_line_installation',
        service_name: 'Ice maker line install',
        system: 'Water Service',
        area: 'Kitchen',
        equipment: 'Ice Maker Line',
        category: 'Laundry / Dishwasher',
        service_type: 'installation',
        unit: 'install',
        customer_description: 'Install an ice maker water supply line for a refrigerator.',
        internal_description: 'Use for ice maker line installation after confirming route, shutoff location, wall/floor access, and connection type.',
        whats_included: ['Install water supply line as scoped', 'Install or connect shutoff as scoped', 'Leak check'],
        whats_not_included: ['Drywall repair', 'Cabinet modification', 'Refrigerator repair', 'Long concealed runs unless specified'],
        common_add_ons: ['Ice maker valve replacement', 'Kitchen shutoff replacement', 'Access opening coordination'],
        recommended_upgrades: ['Dedicated accessible shutoff valve'],
        required_photos: ['Refrigerator location', 'Nearest water source', 'Proposed route', 'Connection point'],
        required_videos: [],
        required_measurements: ['Approximate line length', 'Route access'],
        required_tests: ['Leak check', 'Flow check'],
        required_documents: [],
        warranty: 'Use company-approved workmanship warranty for plumbing connection.',
        permit_required: false,
        code_notes: ['Use approved potable water materials and accessible shutoff'],
        safety_notes: ['Avoid drilling into concealed wiring or piping', 'Protect flooring and cabinets'],
        recommended_tools: ['Tubing cutter', 'Drill', 'Pipe connection tools', 'Stud finder'],
        related_services: ['water_service_kitchen_ice_maker_valve_replacement', 'water_service_kitchen_kitchen_sink_shutoff_replacement'],
        estimate_template: template('Ice maker line install', 'Install refrigerator ice maker water line and verify leak-free operation.'),
        ai_context: 'Ask refrigerator location, nearest water source, route distance, shutoff preference, and whether wall or cabinet access is needed.',
    }),
    item({
        service_id: 'bravo-plumbing-022',
        price_key: 'gas_service_garage_mechanical_gas_leak_diagnostic',
        service_name: 'Gas leak diagnostic',
        system: 'Gas Service',
        area: 'Garage / Mechanical',
        equipment: 'Gas Piping',
        category: 'Gas',
        service_type: 'diagnostic',
        unit: 'diagnostic',
        customer_description: 'Diagnose a suspected gas leak and identify next recommended action.',
        internal_description: 'Use for gas odor or suspected gas leak diagnostic. Prioritize safety, shutoff, ventilation, and utility/emergency coordination when needed.',
        whats_included: ['Safety assessment', 'Accessible gas leak checks', 'Findings summary', 'Repair recommendation'],
        whats_not_included: ['Gas line repair', 'Pressure test unless specified', 'Utility service restoration'],
        common_add_ons: ['Gas shutoff replacement', 'Gas flex connector replacement', 'Gas pressure test'],
        recommended_upgrades: ['Gas shutoff replacement for aged or inaccessible valves'],
        required_photos: ['Gas appliance or line area', 'Shutoff valve', 'Suspected leak point when safe'],
        required_videos: [],
        required_measurements: [],
        required_tests: ['Gas leak detector check', 'Bubble test where appropriate'],
        required_documents: ['Utility red tag or notice when present'],
        warranty: 'Diagnostic visit warranty applies only to evaluation performed.',
        permit_required: false,
        code_notes: ['Gas repairs may require permit or pressure test depending on scope'],
        safety_notes: ['If active gas odor is strong, evacuate and contact emergency utility resources', 'Do not operate switches near active gas leak'],
        recommended_tools: ['Gas leak detector', 'Leak solution', 'Gas shutoff wrench', 'PPE'],
        related_services: ['gas_service_garage_mechanical_gas_shutoff_replacement', 'gas_service_garage_mechanical_gas_pressure_test'],
        estimate_template: template('Gas leak diagnostic', 'Evaluate suspected gas leak and provide repair or safety recommendation.'),
        ai_context: 'Ask odor severity, appliance involved, whether gas is shut off, utility red tag status, and whether occupants are safe.',
    }),
    item({
        service_id: 'bravo-plumbing-023',
        price_key: 'gas_service_garage_mechanical_gas_shutoff_replacement',
        service_name: 'Gas shutoff replacement',
        system: 'Gas Service',
        area: 'Garage / Mechanical',
        equipment: 'Gas Shutoff Valve',
        category: 'Gas',
        service_type: 'replacement',
        unit: 'replacement',
        customer_description: 'Replace an accessible gas shutoff valve.',
        internal_description: 'Use for appliance or branch gas shutoff replacement after confirming gas control, pipe size, and permit/pressure test requirements.',
        whats_included: ['Shut off gas as scoped', 'Replace accessible gas shutoff', 'Leak check connection'],
        whats_not_included: ['Gas line reroute', 'Pressure test unless specified', 'Appliance repair'],
        common_add_ons: ['Gas flex connector replacement', 'Sediment trap installation', 'Gas pressure test'],
        recommended_upgrades: ['Gas flex connector replacement when aged or non-compliant'],
        required_photos: ['Existing shutoff', 'Appliance connection', 'Pipe material and access'],
        required_videos: [],
        required_measurements: ['Pipe size', 'Connector size where relevant'],
        required_tests: ['Leak check', 'Gas operation check where safe'],
        required_documents: ['Permit or red tag notes when applicable'],
        warranty: 'Use company-approved workmanship warranty and manufacturer part warranty.',
        permit_required: false,
        code_notes: ['Confirm local gas valve, connector, and sediment trap requirements'],
        safety_notes: ['Verify gas is off before disassembly', 'Leak test before returning appliance to service'],
        recommended_tools: ['Gas leak detector', 'Pipe wrenches', 'Leak solution', 'Approved gas sealant'],
        related_services: ['gas_service_garage_mechanical_gas_flex_connector_replacement', 'gas_service_garage_mechanical_gas_pressure_test'],
        estimate_template: template('Gas shutoff replacement', 'Replace accessible gas shutoff valve and verify leak-free operation.'),
        ai_context: 'Ask appliance type, shutoff location, gas odor status, pipe size, connector condition, and whether utility has red tagged the system.',
    }),
    item({
        service_id: 'bravo-plumbing-024',
        price_key: 'water_quality_garage_mechanical_whole_home_filter_installation',
        service_name: 'Whole-home filter install',
        system: 'Water Quality',
        area: 'Garage / Mechanical',
        equipment: 'Whole-home Filter',
        category: 'Water Quality',
        service_type: 'installation',
        unit: 'install',
        customer_description: 'Install a whole-home water filtration system in an accessible location.',
        internal_description: 'Use for whole-home filter installation after confirming pipe material, location, bypass needs, drain needs, filter type, and access.',
        whats_included: ['Install filtration equipment as scoped', 'Connect to potable water piping', 'Basic startup and leak check'],
        whats_not_included: ['Electrical work', 'Drain installation unless specified', 'Water softener installation unless included'],
        common_add_ons: ['Bypass valve', 'Pressure regulator replacement', 'Filter cartridge plan'],
        recommended_upgrades: ['Water softener installation', 'PRV replacement when pressure is high'],
        required_photos: ['Proposed install location', 'Main water piping', 'Nearby shutoff and drain options'],
        required_videos: [],
        required_measurements: ['Pipe size', 'Available wall space', 'Water pressure'],
        required_tests: ['Leak check', 'Flow check', 'Pressure check'],
        required_documents: ['Filter model information', 'Maintenance schedule notes'],
        warranty: 'Use company-approved workmanship warranty and manufacturer equipment warranty.',
        permit_required: false,
        code_notes: ['Confirm approved potable water materials and bypass requirements'],
        safety_notes: ['Confirm water shutoff before piping modification', 'Support equipment properly'],
        recommended_tools: ['Pipe cutters', 'Press or solder tools as applicable', 'Level', 'Pressure gauge'],
        related_services: ['water_quality_whole_home_whole_home_filter_service', 'water_service_garage_mechanical_prv_pressure_regulator_replacement'],
        estimate_template: template('Whole-home filter install', 'Install whole-home water filtration equipment and verify leak-free operation.'),
        ai_context: 'Ask water quality goals, pipe material, available space, drain needs, pressure, and cartridge replacement expectations.',
    }),
    item({
        service_id: 'bravo-plumbing-025',
        price_key: 'diagnostics_inspections_whole_home_plumbing_diagnostic',
        service_name: 'Plumbing diagnostic',
        system: 'Diagnostics / Inspections',
        area: 'Whole Home',
        equipment: 'Plumbing System',
        category: 'Diagnostics / Inspections',
        service_type: 'diagnostic',
        unit: 'diagnostic',
        customer_description: 'General plumbing diagnostic visit to evaluate a reported issue.',
        internal_description: 'Use for initial plumbing diagnostic when the specific repair scope is not yet known.',
        whats_included: ['Interview customer', 'Inspect accessible relevant plumbing', 'Perform basic diagnostic checks', 'Recommend next steps'],
        whats_not_included: ['Repairs', 'Parts replacement', 'Camera inspection unless specified', 'Destructive access'],
        common_add_ons: ['Leak detection', 'Water pressure inspection', 'Drain cleaning', 'Fixture repair'],
        recommended_upgrades: ['Plumbing inspection for older homes or repeated issues'],
        required_photos: ['Reported issue area', 'Relevant fixture or piping', 'Visible failure point if present'],
        required_videos: ['Short video of intermittent issue when useful'],
        required_measurements: ['Water pressure when relevant', 'Temperature when relevant'],
        required_tests: ['Basic operation test related to concern', 'Leak check where relevant'],
        required_documents: [],
        warranty: 'Diagnostic visit warranty applies only to the evaluation performed and documented.',
        permit_required: false,
        code_notes: ['Document visible code concerns separately from repair recommendation'],
        safety_notes: ['Stop work and isolate system if unsafe condition is found'],
        recommended_tools: ['Flashlight', 'Moisture meter', 'Pressure gauge', 'Basic hand tools'],
        related_services: ['diagnostics_inspections_whole_home_plumbing_inspection', 'diagnostics_inspections_whole_home_leak_detection'],
        estimate_template: template('Plumbing diagnostic', 'Evaluate reported plumbing concern and provide documented findings and next-step recommendation.'),
        ai_context: 'Ask symptom, affected fixtures, urgency, visible leaks, recent work, home age, and whether the issue is constant or intermittent.',
    }),
];

export function getCatalogItems(): BravoMasterPlumbingCatalogItem[] {
    return [...bravoMasterPlumbingCatalogItems];
}

export function getCatalogItemByPriceKey(priceKey: string): BravoMasterPlumbingCatalogItem | null {
    const normalizedPriceKey = priceKey.trim();

    return bravoMasterPlumbingCatalogItems.find((item) => item.price_key === normalizedPriceKey) || null;
}

export function getCatalogItemsBySystem(system: string): BravoMasterPlumbingCatalogItem[] {
    const normalizedSystem = normalizeSearchText(system);

    return bravoMasterPlumbingCatalogItems.filter((item) => normalizeSearchText(item.system) === normalizedSystem);
}

export function getCatalogItemsByArea(system: string, area: string): BravoMasterPlumbingCatalogItem[] {
    const normalizedSystem = normalizeSearchText(system);
    const normalizedArea = normalizeSearchText(area);

    return bravoMasterPlumbingCatalogItems.filter((item) =>
        normalizeSearchText(item.system) === normalizedSystem &&
        normalizeSearchText(item.area) === normalizedArea
    );
}

export function searchCatalogItems(query: string): BravoMasterPlumbingCatalogItem[] {
    const normalizedQuery = normalizeSearchText(query);

    if (!normalizedQuery) return getCatalogItems();

    return bravoMasterPlumbingCatalogItems.filter((item) =>
        [
            item.service_id,
            item.price_key,
            item.service_name,
            item.system,
            item.area,
            item.equipment,
            item.category,
            item.service_type,
            item.customer_description,
            item.internal_description,
            item.ai_context,
            ...item.whats_included,
            ...item.whats_not_included,
            ...item.common_add_ons,
            ...item.recommended_upgrades,
            ...item.related_services,
        ]
            .map(normalizeSearchText)
            .some((value) => value.includes(normalizedQuery))
    );
}

type BravoCatalogItemSeed = Omit<
    BravoMasterPlumbingCatalogItem,
    | 'version'
    | 'status'
    | 'confidence_level'
    | 'base_price'
    | 'labor_hours'
    | 'material_cost'
    | 'linear_foot_price'
    | 'minimum_price'
    | 'maximum_discount_percent'
    | 'package_discount_percent'
    | 'active'
>;

function item(seed: BravoCatalogItemSeed): BravoMasterPlumbingCatalogItem {
    return {
        ...seed,
        version: catalogVersion,
        status: 'draft',
        confidence_level: 3,
        ...pricingPlaceholder,
        active: true,
    };
}

function template(lineItemTitle: string, defaultScope: string): BravoCatalogEstimateTemplate {
    return {
        line_item_title: lineItemTitle,
        default_scope: defaultScope,
        pricing_notes: ['Pricing fields are intentionally blank until reviewed and approved.'],
    };
}

function normalizeSearchText(value: string) {
    return value.trim().toLowerCase().replace(/[^a-z0-9]+/g, ' ').trim();
}
