import type { BravoKnowledgeEstimateTemplate, BravoKnowledgeObject } from '../bravoKnowledgeEngine';

const knowledgeVersion = '1.0';

const unknownPricing = {
    base_price: null,
    labor_hours: null,
    material_cost: null,
    linear_foot_price: null,
    minimum_price: null,
    maximum_discount_percent: null,
    package_discount_percent: null,
};

export const waterHeaterKnowledgeObjects: BravoKnowledgeObject[] = [
    knowledgeObject({
        service_id: 'bke-water-heater-001',
        price_key: 'water_service_garage_mechanical_standard_tank_water_heater_replacement',
        service_name: 'Standard tank water heater replacement',
        system: 'Water Service',
        area: 'Garage / Mechanical',
        equipment: 'Tank Water Heater',
        category: 'Water Heaters',
        service_type: 'replacement',
        unit: 'replacement',
        customer_description: 'Replace an existing standard residential tank water heater with a comparable tank unit.',
        internal_description: 'Use for like-kind standard tank replacement after confirming tank size, fuel type, venting, access, code needs, and haul-away scope.',
        whats_included: ['Remove existing tank water heater', 'Set replacement tank water heater', 'Reconnect approved water and fuel connections', 'Perform basic startup and leak checks'],
        whats_not_included: ['Major venting changes', 'Electrical upgrades', 'Platform rebuild', 'Permit fees unless specified', 'Drywall or finish repair'],
        common_add_ons: ['Expansion tank install', 'Water heater pan installation', 'Seismic strap installation', 'Water heater code correction'],
        recommended_upgrades: ['Expansion tank install', 'Whole-home filter install', 'Main water shutoff replacement'],
        required_photos: ['Existing water heater label', 'Full installation area', 'Venting or flue', 'Water connections', 'Fuel connection', 'Drain pan area'],
        required_measurements: ['Tank gallon size', 'Water heater height', 'Access width', 'Vent diameter where applicable'],
        required_tests: ['Leak check at water connections', 'Fuel leak check where applicable', 'Hot water operation check', 'Temperature setting confirmation'],
        required_documents: ['Manufacturer model and serial information', 'Permit documentation when required'],
        warranty: 'Use company-approved workmanship warranty and manufacturer equipment warranty.',
        permit_required: true,
        code_notes: ['Confirm local permit requirements', 'Confirm expansion control requirements', 'Confirm seismic restraint requirements where applicable'],
        safety_notes: ['Shut off water and fuel before removal', 'Verify venting and combustion air where applicable', 'Use safe lifting practices'],
        recommended_tools: ['Pipe cutters', 'Adjustable wrenches', 'Level', 'Combustion leak detector where applicable', 'Hand truck'],
        related_services: ['water_service_garage_mechanical_water_heater_expansion_tank_installation', 'water_service_garage_mechanical_water_heater_pan_installation', 'water_service_garage_mechanical_water_heater_seismic_strap_installation'],
        estimate_template: template('Standard tank water heater replacement', 'Replace existing standard tank water heater after confirming site conditions and code requirements.'),
        ai_context: 'Ask for tank gallon size, fuel type, age, venting style, access constraints, permit requirements, expansion tank status, drain pan status, and haul-away needs.',
        training_notes: ['Confirm whether this is like-kind replacement or a change in type or size.', 'Document any code upgrades separately before quoting.', 'Do not promise same-day completion when permit or access issues are unresolved.'],
        reporting_tags: ['water_heater', 'tank_replacement', 'garage_mechanical', 'replacement'],
    }),
    knowledgeObject({
        service_id: 'bke-water-heater-002',
        price_key: 'water_service_garage_mechanical_tankless_water_heater_replacement',
        service_name: 'Tankless water heater replacement',
        system: 'Water Service',
        area: 'Garage / Mechanical',
        equipment: 'Tankless Water Heater',
        category: 'Water Heaters',
        service_type: 'replacement',
        unit: 'replacement',
        customer_description: 'Replace an existing residential tankless water heater.',
        internal_description: 'Use for tankless replacement after confirming model, fuel type, gas sizing, venting, condensate routing, isolation valves, and electrical requirements.',
        whats_included: ['Remove existing tankless unit', 'Install replacement tankless unit', 'Reconnect approved water and fuel connections', 'Perform startup and leak checks'],
        whats_not_included: ['Gas line resizing', 'New vent route', 'Electrical circuit changes', 'Water treatment equipment', 'Condensate drain corrections unless specified'],
        common_add_ons: ['Isolation valve kit', 'Condensate neutralizer', 'Whole-home filter install', 'Gas line correction'],
        recommended_upgrades: ['Whole-home filter install', 'Tankless isolation valve kit', 'Recirculation pump service'],
        required_photos: ['Existing tankless label', 'Full wall mounting area', 'Venting route', 'Gas connection', 'Condensate routing', 'Electrical connection'],
        required_measurements: ['Existing model number', 'Gas pipe size', 'Vent size and route', 'Available wall space'],
        required_tests: ['Leak check', 'Fuel leak check', 'Hot water flow test', 'Startup error code check'],
        required_documents: ['Manufacturer startup information', 'Permit documentation when required'],
        warranty: 'Use company-approved workmanship warranty and manufacturer equipment warranty.',
        permit_required: true,
        code_notes: ['Confirm venting material and termination clearances', 'Confirm condensate disposal requirements', 'Confirm gas sizing if changing model capacity'],
        safety_notes: ['Verify gas shutoff operation', 'Check for combustion safety concerns before startup', 'Do not reuse non-compliant venting'],
        recommended_tools: ['Gas leak detector', 'Combustion analyzer where required', 'Pipe wrenches', 'Level', 'Condensate pH media when needed'],
        related_services: ['water_service_garage_mechanical_recirculation_pump_installation', 'water_quality_garage_mechanical_whole_home_filter_installation', 'gas_service_garage_mechanical_gas_line_repair_linear_foot'],
        estimate_template: template('Tankless water heater replacement', 'Replace existing tankless water heater after confirming venting, fuel, condensate, and access requirements.'),
        ai_context: 'Ask for existing model, fuel type, vent type, gas line size, condensate setup, isolation valve status, water quality, and whether this is like-kind replacement or conversion.',
        training_notes: ['Tankless replacement is not automatically like-kind just because the unit is tankless.', 'Always check venting and condensate details before quoting.', 'Escalate gas sizing uncertainty before final estimate.'],
        reporting_tags: ['water_heater', 'tankless', 'replacement', 'garage_mechanical'],
    }),
    knowledgeObject({
        service_id: 'bke-water-heater-003',
        price_key: 'water_service_garage_mechanical_water_heater_diagnostic',
        service_name: 'Water heater diagnostic',
        system: 'Water Service',
        area: 'Garage / Mechanical',
        equipment: 'Water Heater',
        category: 'Water Heaters',
        service_type: 'diagnostic',
        unit: 'diagnostic',
        customer_description: 'Diagnose water heater performance, leak, ignition, power, temperature, or code concerns.',
        internal_description: 'Use for first-visit troubleshooting before repair or replacement scope is known.',
        whats_included: ['Interview customer about symptoms', 'Inspect accessible water heater components', 'Perform basic operational checks', 'Summarize repair or replacement recommendation'],
        whats_not_included: ['Parts replacement', 'Tank flush', 'Major disassembly', 'Permit fees', 'Hidden condition repair'],
        common_add_ons: ['Water heater flush', 'T&P valve replacement', 'Expansion tank install', 'Drain valve replacement'],
        recommended_upgrades: ['Water heater flush when age and condition allow', 'Expansion tank install when missing or failed', 'Replacement when tank is leaking or unsafe'],
        required_photos: ['Water heater label', 'Full installation area', 'Observed leak or failure point', 'Venting or power/fuel connection where relevant'],
        required_measurements: ['Water temperature if relevant', 'Static water pressure if relevant', 'Unit age'],
        required_tests: ['Visual leak check', 'Power or ignition check where applicable', 'Temperature test where applicable'],
        required_documents: ['Error code or manufacturer diagnostic notes when available'],
        warranty: 'Diagnostic visit warranty applies only to the performed evaluation, not unresolved hidden conditions.',
        permit_required: false,
        code_notes: ['Document visible code concerns separately from diagnostic findings'],
        safety_notes: ['Do not operate unsafe equipment', 'Shut down leaking or unsafe units when needed', 'Escalate active gas concerns immediately'],
        recommended_tools: ['Multimeter', 'Thermometer', 'Pressure gauge', 'Gas leak detector where applicable', 'Flashlight'],
        related_services: ['water_service_garage_mechanical_water_heater_flush', 'water_service_garage_mechanical_water_heater_tp_valve_replacement', 'water_service_garage_mechanical_standard_tank_water_heater_replacement'],
        estimate_template: template('Water heater diagnostic', 'Diagnose water heater issue and provide repair or replacement recommendation.'),
        ai_context: 'Ask about water temperature, leak location, age, fuel type, error codes, power status, recent changes, and whether hot water is fully out or intermittent.',
        training_notes: ['Separate diagnostic facts from recommendations.', 'If tank is leaking from the vessel, do not quote repair as a permanent solution.', 'Record model and serial information whenever visible.'],
        reporting_tags: ['water_heater', 'diagnostic', 'garage_mechanical'],
    }),
    knowledgeObject({
        service_id: 'bke-water-heater-004',
        price_key: 'water_service_garage_mechanical_water_heater_flush',
        service_name: 'Water heater flush',
        system: 'Water Service',
        area: 'Garage / Mechanical',
        equipment: 'Water Heater',
        category: 'Water Heaters',
        service_type: 'maintenance',
        unit: 'service call',
        customer_description: 'Flush sediment from a residential water heater where the condition of the equipment allows.',
        internal_description: 'Use for maintenance flush. Confirm water heater age, drain valve condition, water quality, and whether flushing could worsen an old or compromised tank.',
        whats_included: ['Connect hose to accessible drain valve', 'Flush tank as conditions allow', 'Check visible connections after flush'],
        whats_not_included: ['Replacing failed drain valve', 'Descaling tankless unit', 'Repairing leaks discovered during service', 'Anode rod replacement unless specified'],
        common_add_ons: ['Drain valve replacement', 'Water heater diagnostic', 'Expansion tank inspection'],
        recommended_upgrades: ['Whole-home filter install', 'Expansion tank install', 'Tank replacement when tank condition is poor'],
        required_photos: ['Water heater label', 'Drain valve', 'Flush hose setup', 'Discharge location'],
        required_measurements: ['Tank age', 'Static water pressure when relevant'],
        required_tests: ['Post-service leak check', 'Hot water recovery confirmation where practical'],
        required_documents: [],
        warranty: 'Maintenance service warranty covers workmanship only and does not guarantee future tank condition.',
        permit_required: false,
        code_notes: [],
        safety_notes: ['Use caution with hot water discharge', 'Do not force compromised drain valves', 'Warn customer if old tank condition makes flushing risky'],
        recommended_tools: ['Hose', 'Bucket', 'Channel locks', 'Thermometer', 'PPE'],
        related_services: ['water_service_garage_mechanical_water_heater_drain_valve_replacement', 'water_service_garage_mechanical_water_heater_diagnostic'],
        estimate_template: template('Water heater flush', 'Flush accessible residential water heater and check visible connections after service.'),
        ai_context: 'Ask for tank age, last flush date, sediment symptoms, drain valve condition, water quality, and whether there is a safe discharge point.',
        training_notes: ['Do not oversell flushes on failing tanks.', 'Document pre-existing leaks or corrosion before starting.', 'If drain valve fails, stop and quote repair.'],
        reporting_tags: ['water_heater', 'maintenance', 'flush', 'garage_mechanical'],
    }),
    knowledgeObject({
        service_id: 'bke-water-heater-005',
        price_key: 'water_service_garage_mechanical_water_heater_expansion_tank_installation',
        service_name: 'Expansion tank install',
        system: 'Water Service',
        area: 'Garage / Mechanical',
        equipment: 'Expansion Tank',
        category: 'Water Heaters',
        service_type: 'installation',
        unit: 'install',
        customer_description: 'Install a potable water expansion tank for a residential water heater system.',
        internal_description: 'Use when expansion control is missing, failed, required by code, or needed due to a closed plumbing system.',
        whats_included: ['Install approved potable expansion tank', 'Set precharge as practical', 'Connect to cold water piping', 'Leak check'],
        whats_not_included: ['Replacing water heater', 'PRV replacement', 'Major piping relocation', 'Wall repair'],
        common_add_ons: ['PRV replacement', 'Water pressure inspection', 'Water heater code correction'],
        recommended_upgrades: ['PRV replacement when pressure is high', 'Main water shutoff replacement when shutoff is unreliable'],
        required_photos: ['Water heater area', 'Cold water piping', 'Existing expansion tank if present', 'Installed expansion tank'],
        required_measurements: ['Static water pressure', 'Tank size requirement when known', 'Available mounting space'],
        required_tests: ['Leak check', 'Pressure check', 'Precharge check where practical'],
        required_documents: [],
        warranty: 'Use company-approved workmanship warranty and manufacturer equipment warranty.',
        permit_required: false,
        code_notes: ['Confirm local expansion control requirements', 'Support expansion tank according to manufacturer guidance'],
        safety_notes: ['Confirm water is off before piping modification', 'Support tank properly to avoid pipe strain'],
        recommended_tools: ['Pressure gauge', 'Pipe cutters', 'Adjustable wrenches', 'Air gauge', 'Press or solder tools as applicable'],
        related_services: ['water_service_garage_mechanical_prv_pressure_regulator_replacement', 'diagnostics_inspections_whole_home_water_pressure_inspection'],
        estimate_template: template('Expansion tank install', 'Install potable water expansion tank and verify connection is leak free.'),
        ai_context: 'Ask whether the home has a PRV or closed plumbing system, current water pressure, water heater size, and available mounting location.',
        training_notes: ['Expansion tank sizing and precharge matter.', 'High pressure can indicate a PRV issue that should be quoted separately.', 'Avoid unsupported horizontal installs that strain piping.'],
        reporting_tags: ['water_heater', 'expansion_tank', 'installation', 'code_support'],
    }),
    knowledgeObject({
        service_id: 'bke-water-heater-006',
        price_key: 'water_service_garage_mechanical_water_heater_tp_valve_replacement',
        service_name: 'T&P valve replacement',
        system: 'Water Service',
        area: 'Garage / Mechanical',
        equipment: 'T&P Valve',
        category: 'Water Heaters',
        service_type: 'replacement',
        unit: 'replacement',
        customer_description: 'Replace a water heater temperature and pressure relief valve.',
        internal_description: 'Use for accessible T&P valve replacement after confirming discharge piping, water pressure, thermal expansion conditions, and tank condition.',
        whats_included: ['Remove accessible T&P valve', 'Install approved replacement valve', 'Reconnect or correct discharge connection as scoped', 'Leak check'],
        whats_not_included: ['Expansion tank install', 'PRV replacement', 'Tank replacement', 'Major discharge piping reroute unless specified'],
        common_add_ons: ['Expansion tank install', 'PRV replacement', 'Water pressure inspection'],
        recommended_upgrades: ['Expansion tank install when thermal expansion is suspected', 'PRV replacement when pressure is high'],
        required_photos: ['Existing T&P valve', 'Discharge pipe termination', 'Water heater label', 'Any active discharge'],
        required_measurements: ['Static water pressure', 'Valve size and rating when visible'],
        required_tests: ['Leak check', 'Pressure check', 'Verify no active discharge after replacement where practical'],
        required_documents: [],
        warranty: 'Use company-approved workmanship warranty and manufacturer part warranty.',
        permit_required: false,
        code_notes: ['Discharge piping must terminate safely and comply with local requirements', 'Do not cap or plug relief valve discharge'],
        safety_notes: ['Relief valve discharge can indicate unsafe pressure or temperature', 'Use caution with hot water discharge'],
        recommended_tools: ['Pipe wrench', 'Adjustable wrench', 'Pressure gauge', 'Approved pipe sealant'],
        related_services: ['water_service_garage_mechanical_water_heater_expansion_tank_installation', 'water_service_garage_mechanical_prv_pressure_regulator_replacement'],
        estimate_template: template('T&P valve replacement', 'Replace water heater relief valve and verify safe, leak-free operation.'),
        ai_context: 'Ask whether the valve is leaking, discharging intermittently, capped, missing discharge piping, or connected to an expansion/pressure issue.',
        training_notes: ['A leaking T&P valve may be a symptom, not the root cause.', 'Never cap relief discharge.', 'Check pressure and expansion before assuming the valve alone failed.'],
        reporting_tags: ['water_heater', 'tp_valve', 'safety', 'replacement'],
    }),
    knowledgeObject({
        service_id: 'bke-water-heater-007',
        price_key: 'water_service_garage_mechanical_water_heater_drain_valve_replacement',
        service_name: 'Drain valve replacement',
        system: 'Water Service',
        area: 'Garage / Mechanical',
        equipment: 'Water Heater Drain Valve',
        category: 'Water Heaters',
        service_type: 'replacement',
        unit: 'replacement',
        customer_description: 'Replace a leaking or failed water heater drain valve.',
        internal_description: 'Use for accessible drain valve replacement when tank condition allows safe service.',
        whats_included: ['Drain water as needed', 'Remove accessible drain valve', 'Install replacement drain valve', 'Leak check'],
        whats_not_included: ['Tank replacement', 'Full water heater flush unless specified', 'Repair of tank threads or compromised tank body'],
        common_add_ons: ['Water heater flush', 'Water heater diagnostic', 'Tank replacement if drain valve area is compromised'],
        recommended_upgrades: ['Water heater flush when tank condition allows', 'Water heater replacement when valve failure indicates severe tank deterioration'],
        required_photos: ['Existing drain valve', 'Water heater label', 'Corrosion around valve area'],
        required_measurements: ['Valve connection size when visible', 'Tank age'],
        required_tests: ['Leak check after replacement'],
        required_documents: [],
        warranty: 'Use company-approved workmanship warranty for replacement valve installation.',
        permit_required: false,
        code_notes: [],
        safety_notes: ['Use caution with hot water discharge', 'Do not force severely corroded valves without warning customer about risk'],
        recommended_tools: ['Hose', 'Bucket', 'Pipe wrench', 'Approved replacement drain valve'],
        related_services: ['water_service_garage_mechanical_water_heater_flush', 'water_service_garage_mechanical_water_heater_diagnostic'],
        estimate_template: template('Drain valve replacement', 'Replace accessible water heater drain valve and verify leak-free condition.'),
        ai_context: 'Ask whether the valve leaks, will not close, is plastic or brass, tank age, corrosion level, and whether customer wants flush service too.',
        training_notes: ['Old plastic drain valves can break during service.', 'Document corrosion before attempting removal.', 'Be ready to recommend replacement if the tank body is compromised.'],
        reporting_tags: ['water_heater', 'drain_valve', 'replacement', 'maintenance'],
    }),
    knowledgeObject({
        service_id: 'bke-water-heater-008',
        price_key: 'water_service_garage_mechanical_water_heater_supply_line_replacement',
        service_name: 'Water heater supply line replacement',
        system: 'Water Service',
        area: 'Garage / Mechanical',
        equipment: 'Water Heater Supply Lines',
        category: 'Water Heaters',
        service_type: 'replacement',
        unit: 'replacement',
        customer_description: 'Replace accessible water heater supply connectors.',
        internal_description: 'Use for replacement of hot and/or cold water heater connectors after confirming connector type, pipe material, corrosion, and shutoff access.',
        whats_included: ['Shut off water', 'Replace accessible water heater connector or connectors as scoped', 'Restore water and leak check'],
        whats_not_included: ['Water heater replacement', 'Major piping reroute', 'Main shutoff repair', 'Wall repair'],
        common_add_ons: ['Main water shutoff replacement', 'Expansion tank install', 'Water heater flex connector replacement'],
        recommended_upgrades: ['Main water shutoff replacement when shutoff is unreliable', 'Expansion tank install if missing'],
        required_photos: ['Existing supply connectors', 'Cold and hot piping', 'Water heater top connections', 'Corrosion or leak point'],
        required_measurements: ['Connector length', 'Pipe size and material'],
        required_tests: ['Leak check', 'Hot water operation check when practical'],
        required_documents: [],
        warranty: 'Use company-approved workmanship warranty and manufacturer part warranty.',
        permit_required: false,
        code_notes: ['Use approved potable water connector materials', 'Follow local requirements for flexible connectors'],
        safety_notes: ['Confirm water shutoff before disconnecting connectors', 'Avoid stressing tank nipples or existing piping'],
        recommended_tools: ['Adjustable wrenches', 'Pipe cutters', 'Approved connectors', 'Thread sealant where required'],
        related_services: ['water_service_garage_mechanical_main_water_shutoff_replacement', 'water_service_garage_mechanical_water_heater_expansion_tank_installation'],
        estimate_template: template('Water heater supply line replacement', 'Replace accessible water heater supply connector and verify leak-free operation.'),
        ai_context: 'Ask which connector leaks, connector material, pipe material, water heater age, shutoff reliability, and whether expansion tank piping is involved.',
        training_notes: ['Avoid twisting tank nipples.', 'If corrosion is severe, explain risk before service.', 'Replace compromised connectors rather than over-tightening.'],
        reporting_tags: ['water_heater', 'supply_line', 'replacement', 'leak_repair'],
    }),
    knowledgeObject({
        service_id: 'bke-water-heater-009',
        price_key: 'water_service_garage_mechanical_water_heater_gas_connection',
        service_name: 'Water heater gas connection',
        system: 'Water Service',
        area: 'Garage / Mechanical',
        equipment: 'Water Heater Gas Connection',
        category: 'Gas',
        service_type: 'installation',
        unit: 'install',
        customer_description: 'Connect water heater gas supply to approved shutoff and connector where conditions allow.',
        internal_description: 'Use for gas connection associated with water heater service. Confirm shutoff, connector, sediment trap, pipe sizing, and local pressure test requirements.',
        whats_included: ['Connect approved gas connector as scoped', 'Verify accessible shutoff', 'Leak check connection'],
        whats_not_included: ['Gas line resizing', 'Gas pressure test unless specified', 'Appliance conversion', 'Utility service restoration'],
        common_add_ons: ['Gas shutoff replacement', 'Gas sediment trap installation', 'Gas pressure test'],
        recommended_upgrades: ['Gas shutoff replacement when valve is aged or inaccessible', 'Sediment trap installation when missing and required'],
        required_photos: ['Existing gas shutoff', 'Gas connector', 'Sediment trap area', 'Water heater gas control'],
        required_measurements: ['Gas connector length', 'Gas pipe size'],
        required_tests: ['Gas leak check', 'Appliance startup check where safe'],
        required_documents: ['Permit or pressure test documentation when required'],
        warranty: 'Use company-approved workmanship warranty for gas connection work.',
        permit_required: false,
        code_notes: ['Confirm local connector, shutoff, sediment trap, and pressure test requirements'],
        safety_notes: ['Verify gas is off before disassembly', 'Leak test before returning equipment to service', 'Escalate active gas odor immediately'],
        recommended_tools: ['Gas leak detector', 'Leak solution', 'Pipe wrenches', 'Approved gas connector', 'Gas-rated sealant'],
        related_services: ['gas_service_garage_mechanical_gas_shutoff_replacement', 'gas_service_garage_mechanical_gas_sediment_trap_installation', 'gas_service_garage_mechanical_gas_pressure_test'],
        estimate_template: template('Water heater gas connection', 'Connect approved water heater gas supply components and verify leak-free operation.'),
        ai_context: 'Ask fuel type, connector condition, shutoff location, sediment trap status, gas odor, pipe size, and whether a pressure test is required.',
        training_notes: ['Gas work requires extra documentation and leak testing.', 'Do not reuse questionable gas connectors.', 'Know when local code requires pressure testing or permit.'],
        reporting_tags: ['water_heater', 'gas_connection', 'gas', 'safety'],
    }),
    knowledgeObject({
        service_id: 'bke-water-heater-010',
        price_key: 'water_service_garage_mechanical_water_heater_permit_code_correction',
        service_name: 'Water heater code correction',
        system: 'Water Service',
        area: 'Garage / Mechanical',
        equipment: 'Water Heater',
        category: 'Water Heaters',
        service_type: 'code upgrade',
        unit: 'service call',
        customer_description: 'Correct common water heater installation code items identified during service or inspection.',
        internal_description: 'Use for water heater code correction when the main installation remains serviceable and corrections are clear, accessible, and scoped.',
        whats_included: ['Correct scoped code items', 'Document completed correction', 'Perform relevant leak or operation checks'],
        whats_not_included: ['Full water heater replacement', 'Major venting reroute', 'Structural work', 'Permit fees unless specified'],
        common_add_ons: ['Expansion tank install', 'Seismic strap installation', 'T&P discharge correction', 'Gas sediment trap installation'],
        recommended_upgrades: ['Water heater replacement if existing installation is unsafe or obsolete', 'PRV replacement if pressure issue contributes to code concern'],
        required_photos: ['Code issue before correction', 'Completed correction', 'Water heater label', 'Full installation area'],
        required_measurements: ['Clearances when relevant', 'Discharge pipe routing when relevant', 'Water pressure when relevant'],
        required_tests: ['Leak check', 'Operational check', 'Pressure check when expansion or PRV issue is involved'],
        required_documents: ['Inspection notice or permit correction list when available', 'Completed correction notes'],
        warranty: 'Use company-approved workmanship warranty for corrected scope only.',
        permit_required: true,
        code_notes: ['Confirm local code before correction', 'Document whether permit or inspection is required', 'Do not claim correction of uninspected hidden conditions'],
        safety_notes: ['Unsafe equipment should remain shut down until corrected', 'Escalate combustion, venting, or gas hazards immediately'],
        recommended_tools: ['Code checklist', 'Pressure gauge', 'Gas leak detector where applicable', 'Pipe tools', 'Level'],
        related_services: ['water_service_garage_mechanical_water_heater_expansion_tank_installation', 'water_service_garage_mechanical_water_heater_tp_valve_replacement', 'gas_service_garage_mechanical_gas_sediment_trap_installation'],
        estimate_template: template('Water heater code correction', 'Correct scoped water heater code items and document completed work.'),
        ai_context: 'Ask what code issue was cited, whether there is an inspection notice, water heater age, permit status, and which corrections are requested.',
        training_notes: ['Code corrections must be specific and documented.', 'Do not bundle vague compliance promises into a small repair.', 'If inspection is required, make that visible in the estimate.'],
        reporting_tags: ['water_heater', 'code_correction', 'permit', 'safety'],
    }),
];

type WaterHeaterKnowledgeSeed = Omit<
    BravoKnowledgeObject,
    | 'version'
    | 'status'
    | 'confidence_level'
    | 'base_price'
    | 'labor_hours'
    | 'material_cost'
    | 'linear_foot_price'
    | 'minimum_price'
    | 'maximum_discount_percent'
    | 'package_discount_percent'
    | 'active'
>;

function knowledgeObject(seed: WaterHeaterKnowledgeSeed): BravoKnowledgeObject {
    return {
        ...seed,
        version: knowledgeVersion,
        status: 'draft',
        confidence_level: 3,
        ...unknownPricing,
        active: true,
    };
}

function template(title: string, scopeSummary: string): BravoKnowledgeEstimateTemplate {
    return {
        title,
        scope_summary: scopeSummary,
        default_line_items: [title],
        customer_notes: ['Pricing and final scope require company review before approval.'],
    };
}
