export const AREAS = [
    { name: 'Kitchen', icon: '🍳' },
    { name: 'Pantry', icon: '🥫' },
    { name: 'Dining Room', icon: '🍽️' },
    { name: 'Living Room', icon: '🛋️' },
    { name: 'Family Room', icon: '🏠' },
    { name: 'Office', icon: '💻' },
    { name: 'Master Bedroom', icon: '🛏️' },
    { name: 'Bedroom', icon: '🛌' },
    { name: 'Master Bathroom', icon: '🚿' },
    { name: 'Bathroom', icon: '🚽' },
    { name: 'Laundry', icon: '🧺' },
    { name: 'Garage', icon: '🚗' },
    { name: 'Attic', icon: '📦' },
    { name: 'Hallway', icon: '🚪' },
    { name: 'Entryway', icon: '🔑' },
    { name: 'Utility Room', icon: '🧰' },
    { name: 'Mechanical Room', icon: '⚙️' },
    { name: 'Front Yard', icon: '🌳' },
    { name: 'Back Yard', icon: '🌿' },
    { name: 'Side Yard', icon: '🌱' },
    { name: 'Patio', icon: '🪑' },
    { name: 'Pool Area', icon: '🏊' },
    { name: 'Exterior', icon: '🏡' },
    { name: 'Other', icon: '➕' },
];