export type HomeOSThemeName = 'classic' | 'pastel' | 'ocean' | 'forest' | 'dark' | 'warmBeige' | 'modernGray' | 'navyGold' | 'luxuryBlackGold' | 'contractorBlue' | 'familySoft' | 'highContrast' | 'softGreen' | 'slateDark' | 'desert';

export type HomeOSTheme = {
    name: HomeOSThemeName;
    label: string;
    colors: {
        background: string;
        surface: string;
        surfaceAlt: string;
        text: string;
        mutedText: string;
        border: string;
        primary: string;
        primaryText: string;
        secondaryButton: string;
        secondaryButtonText: string;
        danger: string;
        dangerBackground: string;
        iconBackground: string;
        progressTrack: string;
        progressFill: string;
        overlay: string;
        link: string;
        status: {
            unknown: { background: string; border: string };
            good: { background: string; border: string };
            notInspected: { background: string; border: string };
            needsAttention: { background: string; border: string };
            emergency: { background: string; border: string };
            activeEmergency: { background: string; border: string };
        };
    };
    radii: {
        card: number;
        button: number;
        pill: number;
    };
};

export const DEFAULT_THEME_NAME: HomeOSThemeName = 'classic';

export const homeOSThemes: Record<HomeOSThemeName, HomeOSTheme> = {
    classic: {
        name: 'classic',
        label: 'HomeOS Classic',
        colors: {
            background: '#F3F6FA',
            surface: '#FFFFFF',
            surfaceAlt: '#E7ECF3',
            text: '#071B33',
            mutedText: '#637083',
            border: '#E3E8EF',
            primary: '#071B33',
            primaryText: '#FFFFFF',
            secondaryButton: '#E7ECF3',
            secondaryButtonText: '#071B33',
            danger: '#B00020',
            dangerBackground: '#FFF1F3',
            iconBackground: '#E7ECF3',
            progressTrack: '#E7ECF3',
            progressFill: '#9AA6B2',
            overlay: '#000000',
            link: '#0B5FFF',
            status: {
                unknown: { background: '#FFFFFF', border: '#E3E8EF' },
                good: { background: '#EAF8EF', border: '#BFE8CC' },
                notInspected: { background: '#FFF8DB', border: '#F4E6A0' },
                needsAttention: { background: '#FFF0DD', border: '#F2C28F' },
                emergency: { background: '#FFEAEA', border: '#F1B8B8' },
                activeEmergency: { background: '#FFD6D6', border: '#E25C5C' },
            },
        },
        radii: {
            card: 22,
            button: 18,
            pill: 999,
        },
    },
    pastel: {
        name: 'pastel',
        label: 'Pastel',
        colors: {
            background: '#FFF7FB',
            surface: '#FFFFFF',
            surfaceAlt: '#F7EAF3',
            text: '#30223A',
            mutedText: '#786A84',
            border: '#ECDCE8',
            primary: '#6E4D8B',
            primaryText: '#FFFFFF',
            secondaryButton: '#F2E7F7',
            secondaryButtonText: '#30223A',
            danger: '#B4234D',
            dangerBackground: '#FFF0F4',
            iconBackground: '#F4E7F8',
            progressTrack: '#F2E7F7',
            progressFill: '#C9A8DD',
            overlay: '#17121C',
            link: '#7C3AED',
            status: {
                unknown: { background: '#FFFFFF', border: '#ECDCE8' },
                good: { background: '#ECFAF0', border: '#C7EFD2' },
                notInspected: { background: '#FFF9DE', border: '#F3E6A2' },
                needsAttention: { background: '#FFF0E5', border: '#F2C9A5' },
                emergency: { background: '#FFEAF0', border: '#F0B5C4' },
                activeEmergency: { background: '#FFD7E2', border: '#E66A89' },
            },
        },
        radii: {
            card: 22,
            button: 18,
            pill: 999,
        },
    },
    ocean: {
        name: 'ocean',
        label: 'Ocean',
        colors: {
            background: '#EEF8FB',
            surface: '#FFFFFF',
            surfaceAlt: '#DDF0F7',
            text: '#062B3A',
            mutedText: '#54717C',
            border: '#CCE2EB',
            primary: '#075E73',
            primaryText: '#FFFFFF',
            secondaryButton: '#DDF0F7',
            secondaryButtonText: '#062B3A',
            danger: '#B42318',
            dangerBackground: '#FFF0EF',
            iconBackground: '#DDF0F7',
            progressTrack: '#DDF0F7',
            progressFill: '#63AFC3',
            overlay: '#03171F',
            link: '#037DA0',
            status: {
                unknown: { background: '#FFFFFF', border: '#CCE2EB' },
                good: { background: '#E7F8F0', border: '#BFEAD2' },
                notInspected: { background: '#FFF8DB', border: '#F1E19A' },
                needsAttention: { background: '#FFF0DD', border: '#EBC08F' },
                emergency: { background: '#FFE9E6', border: '#EEB2AA' },
                activeEmergency: { background: '#FFD4CC', border: '#E96A5B' },
            },
        },
        radii: {
            card: 22,
            button: 18,
            pill: 999,
        },
    },
    forest: {
        name: 'forest',
        label: 'Forest',
        colors: {
            background: '#F1F7F0',
            surface: '#FFFFFF',
            surfaceAlt: '#E2EEDC',
            text: '#17331F',
            mutedText: '#627464',
            border: '#D6E4D0',
            primary: '#234F2F',
            primaryText: '#FFFFFF',
            secondaryButton: '#E2EEDC',
            secondaryButtonText: '#17331F',
            danger: '#B42318',
            dangerBackground: '#FFF0EF',
            iconBackground: '#E2EEDC',
            progressTrack: '#E2EEDC',
            progressFill: '#84A977',
            overlay: '#08150C',
            link: '#2E7D32',
            status: {
                unknown: { background: '#FFFFFF', border: '#D6E4D0' },
                good: { background: '#E5F7E8', border: '#B8E2BF' },
                notInspected: { background: '#FFF8DB', border: '#EBDFA0' },
                needsAttention: { background: '#FFF0DD', border: '#E9C08D' },
                emergency: { background: '#FFE9E6', border: '#EEB2AA' },
                activeEmergency: { background: '#FFD4CC', border: '#E96A5B' },
            },
        },
        radii: {
            card: 22,
            button: 18,
            pill: 999,
        },
    },
    dark: {
        name: 'dark',
        label: 'Dark',
        colors: {
            background: '#0C1118',
            surface: '#151C26',
            surfaceAlt: '#222C38',
            text: '#F5F7FA',
            mutedText: '#A9B4C2',
            border: '#2C3745',
            primary: '#F5F7FA',
            primaryText: '#07111F',
            secondaryButton: '#222C38',
            secondaryButtonText: '#F5F7FA',
            danger: '#FF8A8A',
            dangerBackground: '#3B1820',
            iconBackground: '#222C38',
            progressTrack: '#222C38',
            progressFill: '#7D8B9A',
            overlay: '#000000',
            link: '#8AB4FF',
            status: {
                unknown: { background: '#151C26', border: '#2C3745' },
                good: { background: '#163224', border: '#2E6B45' },
                notInspected: { background: '#383219', border: '#71642A' },
                needsAttention: { background: '#432B18', border: '#8A5A2B' },
                emergency: { background: '#3B1820', border: '#7F3442' },
                activeEmergency: { background: '#561C22', border: '#D45C68' },
            },
        },
        radii: {
            card: 22,
            button: 18,
            pill: 999,
        },
    },
    warmBeige: {
        name: 'warmBeige',
        label: 'Warm Beige',
        colors: {
            background: '#F7F0E6',
            surface: '#FFFDF8',
            surfaceAlt: '#EDE1D0',
            text: '#2E241B',
            mutedText: '#76695C',
            border: '#E2D2BD',
            primary: '#6B4F32',
            primaryText: '#FFFFFF',
            secondaryButton: '#EDE1D0',
            secondaryButtonText: '#2E241B',
            danger: '#B42318',
            dangerBackground: '#FFF0EF',
            iconBackground: '#EDE1D0',
            progressTrack: '#EDE1D0',
            progressFill: '#B99870',
            overlay: '#1E1710',
            link: '#8A5A20',
            status: {
                unknown: { background: '#FFFDF8', border: '#E2D2BD' },
                good: { background: '#EAF7E8', border: '#BFDDB9' },
                notInspected: { background: '#FFF7D6', border: '#EAD891' },
                needsAttention: { background: '#FFEBD6', border: '#E4B07A' },
                emergency: { background: '#FFE7E3', border: '#E8AAA2' },
                activeEmergency: { background: '#FFD0C8', border: '#D95D4F' },
            },
        },
        radii: {
            card: 22,
            button: 18,
            pill: 999,
        },
    },
    modernGray: {
        name: 'modernGray',
        label: 'Modern Gray',
        colors: {
            background: '#F4F5F7',
            surface: '#FFFFFF',
            surfaceAlt: '#E6E8EB',
            text: '#1F2933',
            mutedText: '#68717D',
            border: '#D9DEE5',
            primary: '#2F3A46',
            primaryText: '#FFFFFF',
            secondaryButton: '#E6E8EB',
            secondaryButtonText: '#1F2933',
            danger: '#B42318',
            dangerBackground: '#FFF0EF',
            iconBackground: '#E6E8EB',
            progressTrack: '#E6E8EB',
            progressFill: '#9AA3AD',
            overlay: '#0E1114',
            link: '#2563EB',
            status: {
                unknown: { background: '#FFFFFF', border: '#D9DEE5' },
                good: { background: '#E8F7EE', border: '#B9DEC8' },
                notInspected: { background: '#FFF8DB', border: '#E9DFA0' },
                needsAttention: { background: '#FFF0DD', border: '#E7BC86' },
                emergency: { background: '#FFE9E6', border: '#EEB2AA' },
                activeEmergency: { background: '#FFD4CC', border: '#E96A5B' },
            },
        },
        radii: {
            card: 18,
            button: 14,
            pill: 999,
        },
    },
    navyGold: {
        name: 'navyGold',
        label: 'Navy Gold',
        colors: {
            background: '#F2F5FA',
            surface: '#FFFFFF',
            surfaceAlt: '#E3E8F0',
            text: '#071B33',
            mutedText: '#617083',
            border: '#D8DEE8',
            primary: '#0B1F3A',
            primaryText: '#F9D976',
            secondaryButton: '#E8EDF5',
            secondaryButtonText: '#071B33',
            danger: '#B42318',
            dangerBackground: '#FFF0EF',
            iconBackground: '#E8EDF5',
            progressTrack: '#E8EDF5',
            progressFill: '#C6A84F',
            overlay: '#020817',
            link: '#A47B00',
            status: {
                unknown: { background: '#FFFFFF', border: '#D8DEE8' },
                good: { background: '#E8F7EE', border: '#B9DEC8' },
                notInspected: { background: '#FFF8DA', border: '#EAD371' },
                needsAttention: { background: '#FFF0DD', border: '#E5B06F' },
                emergency: { background: '#FFE9E6', border: '#EEB2AA' },
                activeEmergency: { background: '#FFD4CC', border: '#E96A5B' },
            },
        },
        radii: {
            card: 22,
            button: 18,
            pill: 999,
        },
    },
    luxuryBlackGold: {
        name: 'luxuryBlackGold',
        label: 'Luxury Black Gold',
        colors: {
            background: '#090909',
            surface: '#151515',
            surfaceAlt: '#24201A',
            text: '#F8F3E7',
            mutedText: '#B8AA92',
            border: '#3A3326',
            primary: '#D4AF37',
            primaryText: '#111111',
            secondaryButton: '#24201A',
            secondaryButtonText: '#F8F3E7',
            danger: '#FF8A8A',
            dangerBackground: '#3A1616',
            iconBackground: '#24201A',
            progressTrack: '#24201A',
            progressFill: '#D4AF37',
            overlay: '#000000',
            link: '#F3C94D',
            status: {
                unknown: { background: '#151515', border: '#3A3326' },
                good: { background: '#17331F', border: '#3E8A55' },
                notInspected: { background: '#3C3212', border: '#B99A31' },
                needsAttention: { background: '#442A13', border: '#B8752B' },
                emergency: { background: '#3A1616', border: '#8B3434' },
                activeEmergency: { background: '#581B1B', border: '#E15B5B' },
            },
        },
        radii: {
            card: 24,
            button: 18,
            pill: 999,
        },
    },
    contractorBlue: {
        name: 'contractorBlue',
        label: 'Contractor Blue',
        colors: {
            background: '#EEF4FA',
            surface: '#FFFFFF',
            surfaceAlt: '#DCEAF7',
            text: '#102A43',
            mutedText: '#5B7083',
            border: '#C9D9E8',
            primary: '#145DA0',
            primaryText: '#FFFFFF',
            secondaryButton: '#DCEAF7',
            secondaryButtonText: '#102A43',
            danger: '#B42318',
            dangerBackground: '#FFF0EF',
            iconBackground: '#DCEAF7',
            progressTrack: '#DCEAF7',
            progressFill: '#4B91C9',
            overlay: '#061A2D',
            link: '#0B69B7',
            status: {
                unknown: { background: '#FFFFFF', border: '#C9D9E8' },
                good: { background: '#E7F8F0', border: '#BFEAD2' },
                notInspected: { background: '#FFF8DB', border: '#F1E19A' },
                needsAttention: { background: '#FFF0DD', border: '#EBC08F' },
                emergency: { background: '#FFE9E6', border: '#EEB2AA' },
                activeEmergency: { background: '#FFD4CC', border: '#E96A5B' },
            },
        },
        radii: {
            card: 18,
            button: 14,
            pill: 999,
        },
    },
    familySoft: {
        name: 'familySoft',
        label: 'Family Soft',
        colors: {
            background: '#F8F6FF',
            surface: '#FFFFFF',
            surfaceAlt: '#ECE7FA',
            text: '#25213A',
            mutedText: '#706A86',
            border: '#DED7F0',
            primary: '#5B55A3',
            primaryText: '#FFFFFF',
            secondaryButton: '#ECE7FA',
            secondaryButtonText: '#25213A',
            danger: '#B4234D',
            dangerBackground: '#FFF0F4',
            iconBackground: '#ECE7FA',
            progressTrack: '#ECE7FA',
            progressFill: '#A7A0D8',
            overlay: '#161326',
            link: '#5B55A3',
            status: {
                unknown: { background: '#FFFFFF', border: '#DED7F0' },
                good: { background: '#ECFAF0', border: '#C7EFD2' },
                notInspected: { background: '#FFF9DE', border: '#F3E6A2' },
                needsAttention: { background: '#FFF0E5', border: '#F2C9A5' },
                emergency: { background: '#FFEAF0', border: '#F0B5C4' },
                activeEmergency: { background: '#FFD7E2', border: '#E66A89' },
            },
        },
        radii: {
            card: 26,
            button: 20,
            pill: 999,
        },
    },
    highContrast: {
        name: 'highContrast',
        label: 'High Contrast',
        colors: {
            background: '#000000',
            surface: '#111111',
            surfaceAlt: '#222222',
            text: '#FFFFFF',
            mutedText: '#D6D6D6',
            border: '#FFFFFF',
            primary: '#FFFF00',
            primaryText: '#000000',
            secondaryButton: '#222222',
            secondaryButtonText: '#FFFFFF',
            danger: '#FF4D4D',
            dangerBackground: '#330000',
            iconBackground: '#222222',
            progressTrack: '#333333',
            progressFill: '#FFFF00',
            overlay: '#000000',
            link: '#66B2FF',
            status: {
                unknown: { background: '#111111', border: '#FFFFFF' },
                good: { background: '#003B1F', border: '#00E676' },
                notInspected: { background: '#3B3300', border: '#FFFF00' },
                needsAttention: { background: '#3B1F00', border: '#FFB020' },
                emergency: { background: '#330000', border: '#FF4D4D' },
                activeEmergency: { background: '#5C0000', border: '#FF8080' },
            },
        },
        radii: {
            card: 10,
            button: 8,
            pill: 999,
        },
    },
    softGreen: {
        name: 'softGreen',
        label: 'Soft Green',
        colors: {
            background: '#F4FAF2',
            surface: '#FFFFFF',
            surfaceAlt: '#E6F1E1',
            text: '#1D3423',
            mutedText: '#667866',
            border: '#D8E8D0',
            primary: '#3B6B3B',
            primaryText: '#FFFFFF',
            secondaryButton: '#E6F1E1',
            secondaryButtonText: '#1D3423',
            danger: '#B42318',
            dangerBackground: '#FFF0EF',
            iconBackground: '#E6F1E1',
            progressTrack: '#E6F1E1',
            progressFill: '#8DB77E',
            overlay: '#0C180D',
            link: '#2E7D32',
            status: {
                unknown: { background: '#FFFFFF', border: '#D8E8D0' },
                good: { background: '#E5F7E8', border: '#B8E2BF' },
                notInspected: { background: '#FFF8DB', border: '#EBDFA0' },
                needsAttention: { background: '#FFF0DD', border: '#E9C08D' },
                emergency: { background: '#FFE9E6', border: '#EEB2AA' },
                activeEmergency: { background: '#FFD4CC', border: '#E96A5B' },
            },
        },
        radii: {
            card: 24,
            button: 18,
            pill: 999,
        },
    },
    slateDark: {
        name: 'slateDark',
        label: 'Slate Dark',
        colors: {
            background: '#10151D',
            surface: '#19212C',
            surfaceAlt: '#273241',
            text: '#F4F7FB',
            mutedText: '#AAB6C5',
            border: '#344255',
            primary: '#9CC9FF',
            primaryText: '#07111F',
            secondaryButton: '#273241',
            secondaryButtonText: '#F4F7FB',
            danger: '#FF8A8A',
            dangerBackground: '#3B1820',
            iconBackground: '#273241',
            progressTrack: '#273241',
            progressFill: '#7EA6D8',
            overlay: '#000000',
            link: '#9CC9FF',
            status: {
                unknown: { background: '#19212C', border: '#344255' },
                good: { background: '#163224', border: '#2E6B45' },
                notInspected: { background: '#383219', border: '#71642A' },
                needsAttention: { background: '#432B18', border: '#8A5A2B' },
                emergency: { background: '#3B1820', border: '#7F3442' },
                activeEmergency: { background: '#561C22', border: '#D45C68' },
            },
        },
        radii: {
            card: 20,
            button: 16,
            pill: 999,
        },
    },
    desert: {
        name: 'desert',
        label: 'Desert',
        colors: {
            background: '#FBF1E3',
            surface: '#FFFDF8',
            surfaceAlt: '#F1DEC4',
            text: '#3B2616',
            mutedText: '#7D6654',
            border: '#E5CBAA',
            primary: '#9A5F2E',
            primaryText: '#FFFFFF',
            secondaryButton: '#F1DEC4',
            secondaryButtonText: '#3B2616',
            danger: '#B42318',
            dangerBackground: '#FFF0EF',
            iconBackground: '#F1DEC4',
            progressTrack: '#F1DEC4',
            progressFill: '#C98E55',
            overlay: '#1D1108',
            link: '#A65F1B',
            status: {
                unknown: { background: '#FFFDF8', border: '#E5CBAA' },
                good: { background: '#EAF7E8', border: '#BFDDB9' },
                notInspected: { background: '#FFF7D6', border: '#EAD891' },
                needsAttention: { background: '#FFE6CF', border: '#E7A96B' },
                emergency: { background: '#FFE7E3', border: '#E8AAA2' },
                activeEmergency: { background: '#FFD0C8', border: '#D95D4F' },
            },
        },
        radii: {
            card: 22,
            button: 18,
            pill: 999,
        },
    },
};

export const themeOptions = Object.values(homeOSThemes);

export function isHomeOSThemeName(value: string | null): value is HomeOSThemeName {
    return !!value && value in homeOSThemes;
}
